/* AUTO-GENERATED by scripts/buildAnatomyV2.mjs. */
import type { AnatomyV2Source } from './anatomyV2Types';

export const ANATOMY_V2_FRONT = {
  "view": "front",
  "viewBox": [
    0,
    0,
    220,
    500
  ],
  "shapes": [
    {
      "id": "silhouette_front",
      "d": "M110 12C88 12 76 28 78 50c1 13 7 24 15 31-20 8-36 25-42 50l-14 65c-3 15 2 24 11 26l14-2-1 83 12 154c1 18 12 30 24 30 9 0 13-8 13-21 0 13 4 21 13 21 12 0 23-12 24-30l12-154-1-83 14 2c9-2 14-11 11-26l-14-65c-6-25-22-42-42-50 8-7 14-18 15-31 2-22-10-38-32-38Z",
      "fill": "#20252B"
    },
    {
      "id": "upper_chest_front_left",
      "d": "M82 104c8-9 17-13 27-13v24c-12 0-21 3-29 8Z",
      "fill": "#525C66",
      "muscleId": "upper_chest",
      "view": "front",
      "side": "left"
    },
    {
      "id": "upper_chest_front_right",
      "d": "M138 104c-8-9-17-13-27-13v24c12 0 21 3 29 8Z",
      "fill": "#525C66",
      "muscleId": "upper_chest",
      "view": "front",
      "side": "right"
    },
    {
      "id": "chest_front_left",
      "d": "M79 126c9-7 19-10 30-10v45c-16-1-27-8-33-20Z",
      "fill": "#525C66",
      "muscleId": "chest",
      "view": "front",
      "side": "left"
    },
    {
      "id": "chest_front_right",
      "d": "M141 126c-9-7-19-10-30-10v45c16-1 27-8 33-20Z",
      "fill": "#525C66",
      "muscleId": "chest",
      "view": "front",
      "side": "right"
    },
    {
      "id": "front_delts_front_left",
      "d": "M64 111c7-9 13-12 20-10l-6 42-14-2Z",
      "fill": "#525C66",
      "muscleId": "front_delts",
      "view": "front",
      "side": "left"
    },
    {
      "id": "front_delts_front_right",
      "d": "M156 111c-7-9-13-12-20-10l6 42 14-2Z",
      "fill": "#525C66",
      "muscleId": "front_delts",
      "view": "front",
      "side": "right"
    },
    {
      "id": "side_delts_front_left",
      "d": "M54 121c3-8 7-14 11-18l-1 39-10 18Z",
      "fill": "#525C66",
      "muscleId": "side_delts",
      "view": "front",
      "side": "left"
    },
    {
      "id": "side_delts_front_right",
      "d": "M166 121c-3-8-7-14-11-18l1 39 10 18Z",
      "fill": "#525C66",
      "muscleId": "side_delts",
      "view": "front",
      "side": "right"
    },
    {
      "id": "biceps_front_left",
      "d": "M53 151l12-5 5 52-14 7Z",
      "fill": "#525C66",
      "muscleId": "biceps",
      "view": "front",
      "side": "left"
    },
    {
      "id": "biceps_front_right",
      "d": "M167 151l-12-5-5 52 14 7Z",
      "fill": "#525C66",
      "muscleId": "biceps",
      "view": "front",
      "side": "right"
    },
    {
      "id": "forearms_front_left",
      "d": "M55 208l15-5 5 65-13 11Z",
      "fill": "#525C66",
      "muscleId": "forearms",
      "view": "front",
      "side": "left"
    },
    {
      "id": "forearms_front_right",
      "d": "M165 208l-15-5-5 65 13 11Z",
      "fill": "#525C66",
      "muscleId": "forearms",
      "view": "front",
      "side": "right"
    },
    {
      "id": "abs_front_center",
      "d": "M94 166h32l-3 99-13 17-13-17Z",
      "fill": "#525C66",
      "muscleId": "abs",
      "view": "front",
      "side": "center"
    },
    {
      "id": "obliques_front_left",
      "d": "M78 161l14 6 3 98-18-21Z",
      "fill": "#525C66",
      "muscleId": "obliques",
      "view": "front",
      "side": "left"
    },
    {
      "id": "obliques_front_right",
      "d": "M142 161l-14 6-3 98 18-21Z",
      "fill": "#525C66",
      "muscleId": "obliques",
      "view": "front",
      "side": "right"
    },
    {
      "id": "hip_flexors_front_left",
      "d": "M82 263l27 21-17 29-15-13Z",
      "fill": "#525C66",
      "muscleId": "hip_flexors",
      "view": "front",
      "side": "left"
    },
    {
      "id": "hip_flexors_front_right",
      "d": "M138 263l-27 21 17 29 15-13Z",
      "fill": "#525C66",
      "muscleId": "hip_flexors",
      "view": "front",
      "side": "right"
    },
    {
      "id": "adductors_front_left",
      "d": "M94 305l15-17-4 103-15-5Z",
      "fill": "#525C66",
      "muscleId": "adductors",
      "view": "front",
      "side": "left"
    },
    {
      "id": "adductors_front_right",
      "d": "M126 305l-15-17 4 103 15-5Z",
      "fill": "#525C66",
      "muscleId": "adductors",
      "view": "front",
      "side": "right"
    },
    {
      "id": "quads_front_left",
      "d": "M77 307l15-4 12 90-25 2Z",
      "fill": "#525C66",
      "muscleId": "quads",
      "view": "front",
      "side": "left"
    },
    {
      "id": "quads_front_right",
      "d": "M143 307l-15-4-12 90 25 2Z",
      "fill": "#525C66",
      "muscleId": "quads",
      "view": "front",
      "side": "right"
    },
    {
      "id": "calves_front_left",
      "d": "M80 402h22l-5 70-17-4Z",
      "fill": "#525C66",
      "muscleId": "calves",
      "view": "front",
      "side": "left"
    },
    {
      "id": "calves_front_right",
      "d": "M140 402h-22l5 70 17-4Z",
      "fill": "#525C66",
      "muscleId": "calves",
      "view": "front",
      "side": "right"
    }
  ]
} as const satisfies AnatomyV2Source;
