/* AUTO-GENERATED by scripts/buildAnatomyV2.mjs. */
import type { AnatomyV2Source } from './anatomyV2Types';

export const ANATOMY_V2_BACK = {
  "view": "back",
  "viewBox": [
    0,
    0,
    220,
    500
  ],
  "shapes": [
    {
      "id": "silhouette_back",
      "d": "M110 12C88 12 76 28 78 50c1 13 7 24 15 31-20 8-36 25-42 50l-14 65c-3 15 2 24 11 26l14-2-1 83 12 154c1 18 12 30 24 30 9 0 13-8 13-21 0 13 4 21 13 21 12 0 23-12 24-30l12-154-1-83 14 2c9-2 14-11 11-26l-14-65c-6-25-22-42-42-50 8-7 14-18 15-31 2-22-10-38-32-38Z",
      "fill": "#20252B"
    },
    {
      "id": "traps_back_center",
      "d": "M91 82l19 13 19-13 10 54-29 24-29-24Z",
      "fill": "#525C66",
      "muscleId": "traps",
      "view": "back",
      "side": "center"
    },
    {
      "id": "rear_delts_back_left",
      "d": "M64 108c7-8 15-12 22-9l-6 43-16-1Z",
      "fill": "#525C66",
      "muscleId": "rear_delts",
      "view": "back",
      "side": "left"
    },
    {
      "id": "rear_delts_back_right",
      "d": "M156 108c-7-8-15-12-22-9l6 43 16-1Z",
      "fill": "#525C66",
      "muscleId": "rear_delts",
      "view": "back",
      "side": "right"
    },
    {
      "id": "side_delts_back_left",
      "d": "M54 121c3-8 7-14 11-18l-1 39-10 18Z",
      "fill": "#525C66",
      "muscleId": "side_delts",
      "view": "back",
      "side": "left"
    },
    {
      "id": "side_delts_back_right",
      "d": "M166 121c-3-8-7-14-11-18l1 39 10 18Z",
      "fill": "#525C66",
      "muscleId": "side_delts",
      "view": "back",
      "side": "right"
    },
    {
      "id": "lats_back_left",
      "d": "M77 142l31 19-6 86-28-35Z",
      "fill": "#525C66",
      "muscleId": "lats",
      "view": "back",
      "side": "left"
    },
    {
      "id": "lats_back_right",
      "d": "M143 142l-31 19 6 86 28-35Z",
      "fill": "#525C66",
      "muscleId": "lats",
      "view": "back",
      "side": "right"
    },
    {
      "id": "lower_back_back_center",
      "d": "M103 164h14l8 92-15 25-15-25Z",
      "fill": "#525C66",
      "muscleId": "lower_back",
      "view": "back",
      "side": "center"
    },
    {
      "id": "triceps_back_left",
      "d": "M53 151l12-5 5 52-14 7Z",
      "fill": "#525C66",
      "muscleId": "triceps",
      "view": "back",
      "side": "left"
    },
    {
      "id": "triceps_back_right",
      "d": "M167 151l-12-5-5 52 14 7Z",
      "fill": "#525C66",
      "muscleId": "triceps",
      "view": "back",
      "side": "right"
    },
    {
      "id": "forearms_back_left",
      "d": "M55 208l15-5 5 65-13 11Z",
      "fill": "#525C66",
      "muscleId": "forearms",
      "view": "back",
      "side": "left"
    },
    {
      "id": "forearms_back_right",
      "d": "M165 208l-15-5-5 65 13 11Z",
      "fill": "#525C66",
      "muscleId": "forearms",
      "view": "back",
      "side": "right"
    },
    {
      "id": "glutes_back_left",
      "d": "M76 263l33 19-4 48-31-18Z",
      "fill": "#525C66",
      "muscleId": "glutes",
      "view": "back",
      "side": "left"
    },
    {
      "id": "glutes_back_right",
      "d": "M144 263l-33 19 4 48 31-18Z",
      "fill": "#525C66",
      "muscleId": "glutes",
      "view": "back",
      "side": "right"
    },
    {
      "id": "hamstrings_back_left",
      "d": "M77 329l28 5-2 61-24-1Z",
      "fill": "#525C66",
      "muscleId": "hamstrings",
      "view": "back",
      "side": "left"
    },
    {
      "id": "hamstrings_back_right",
      "d": "M143 329l-28 5 2 61 24-1Z",
      "fill": "#525C66",
      "muscleId": "hamstrings",
      "view": "back",
      "side": "right"
    },
    {
      "id": "calves_back_left",
      "d": "M80 402h22l-5 70-17-4Z",
      "fill": "#525C66",
      "muscleId": "calves",
      "view": "back",
      "side": "left"
    },
    {
      "id": "calves_back_right",
      "d": "M140 402h-22l5 70 17-4Z",
      "fill": "#525C66",
      "muscleId": "calves",
      "view": "back",
      "side": "right"
    }
  ]
} as const satisfies AnatomyV2Source;
