
import { classifyMeasurement, type MeasurementSpec } from '../lib/measurement';
import { NEW_EXERCISES } from './new_exercises';
import { NEW_EXERCISES_V2 } from './new_exercises_v2';
import { NEW_EXERCISES_V3 } from './new_exercises_v3';
export type GrupaMusculara = string;
export type Echipament = string;

export type Categorie =
  | 'piept' | 'spate' | 'picioare' | 'umeri' | 'brate'
  | 'abdomen' | 'cardio' | 'full-body' | 'mobilitate'
  | 'superior' | 'inferior' | 'core' | 'corp_intreg';

export type Dificultate = 'usor' | 'mediu' | 'greu';

export interface CategorieInfo {
  id: Categorie;
  nume: string;
  emoji?: string;
  grupe?: string[];
}

export interface MuscleActivation {
  muscle: string;
  role: 'primary' | 'secondary' | 'stabilizer';
  factor: number;
}

export interface Exercitiu {
  id: string;
  nume: string;
  categorie: Categorie;
  grupe: string[];
  muscleActivations?: MuscleActivation[];
  dificultate: Dificultate;
  echipament?: string;
  met: number;
  caloriiPeMinut?: number;
  descriere?: string;
  instructiuni?: string[];
  muschiTinta?: Record<string, number>;
  target_muscles?: string[];
  activation?: Partial<Record<string, number>>;
  masurare?: MeasurementSpec;
  greseliComune?: string[];
  sfaturi?: string[];
  seriiDefault: number;
  repetariDefault: number;
  icon?: string;
}

export const CATEGORII: CategorieInfo[] = [
  { id: 'piept', nume: 'Piept', emoji: '💪', grupe: ['pectorali', 'triceps', 'deltoid anterior'] },
  { id: 'spate', nume: 'Spate', emoji: '🔙', grupe: ['dorsali', 'trapez', 'romboizi', 'biceps'] },
  { id: 'picioare', nume: 'Picioare', emoji: '🦵', grupe: ['cvadriceps', 'ischiogambieri', 'fesieri', 'gambe'] },
  { id: 'umeri', nume: 'Umeri', emoji: '🏋️', grupe: ['deltoizi', 'trapez'] },
  { id: 'brate', nume: 'Brațe', emoji: '💪', grupe: ['biceps', 'triceps', 'brahial'] },
  { id: 'abdomen', nume: 'Abdomen', emoji: '🔥', grupe: ['abdomeni', 'oblici', 'core'] },
  { id: 'cardio', nume: 'Cardio', emoji: '🏃', grupe: ['cardio', 'picioare'] },
  { id: 'full-body', nume: 'Full Body', emoji: '⚡', grupe: ['corp_intreg', 'core', 'umeri', 'picioare'] },
  { id: 'mobilitate', nume: 'Mobilitate', emoji: '🧘', grupe: ['mobilitate', 'femurali', 'coloană'] },
  // Categorii suplimentare folosite de exerciții
  { id: 'superior', nume: 'Partea Superioară', emoji: '🔼', grupe: ['piept', 'spate', 'umeri', 'brate'] },
  { id: 'inferior', nume: 'Partea Inferioară', emoji: '🔽', grupe: ['picioare', 'fesieri', 'gambe'] },
  { id: 'core', nume: 'Core', emoji: '🎯', grupe: ['abdomeni', 'oblici', 'lombari'] },
  { id: 'corp_intreg', nume: 'Corp Întreg', emoji: '⚡', grupe: ['full-body', 'core', 'picioare', 'umeri'] },
];

export const calculeazaCaloriiArse = (met: number, greutateKg: number, minute: number): number =>
  Math.round((met * 3.5 * greutateKg) / 200 * minute);

export const EXERCITII: Exercitiu[] = [
  // ---- PIEPT ----
  {
    id: 'impins-banca-plat',
    nume: 'Împins la piept cu bara (plat)',
    categorie: 'piept',
    grupe: ['pectorali', 'triceps', 'deltoid anterior'],
    dificultate: 'mediu',
    echipament: 'bară',
    met: 5,
    caloriiPeMinut: 7,
    seriiDefault: 4,
    repetariDefault: 10,
    muschiTinta: { pectorali: 100, triceps: 75, deltoid_anterior: 75, abdomen: 40 },
    descriere: 'Exercițiul de bază pentru masa pectoralilor.',
    instructiuni: [
      'Întins pe bancă, priza puțin mai lată decât umerii.',
      'Coboară bara controlat până la piept.',
      'Împinge exploziv, fără să blochezi brusc coatele.',
    ],
    greseliComune: ['Ridici fundul de pe bancă', 'Cobori bara prea repede'],
  },
  {
    id: 'impins-inclinat-gantere',
    nume: 'Împins înclinat cu gantere',
    categorie: 'piept',
    grupe: ['pectoral superior', 'deltoid anterior'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 5,
    caloriiPeMinut: 7,
    seriiDefault: 3,
    repetariDefault: 12,
    descriere: 'Accent pe partea superioară a pieptului.',
    instructiuni: [
      'Bancă la 30-45 grade.',
      'Împinge ganterele deasupra pieptului.',
      'Coboară până simți întindere.',
    ],
  },
  {
    id: 'impins-declinat',
    nume: 'Împins declinat cu bara',
    categorie: 'piept',
    grupe: ['pectoral inferior', 'triceps'],
    dificultate: 'mediu',
    echipament: 'bară',
    met: 5,
    caloriiPeMinut: 7,
    seriiDefault: 3,
    repetariDefault: 10,
    descriere: 'Țintește partea inferioară a pieptului.',
  },
  {
    id: 'flotari',
    nume: 'Flotări',
    categorie: 'piept',
    grupe: ['pectorali', 'triceps', 'core'],
    dificultate: 'usor',
    echipament: 'greutate corporală',
    met: 3.8,
    caloriiPeMinut: 7,
    seriiDefault: 3,
    repetariDefault: 15,
    descriere: 'Clasicul care merge oriunde.',
    instructiuni: [
      'Corp drept, mâinile sub umeri.',
      'Coboară până pieptul aproape atinge solul.',
      'Împinge înapoi, fără să lași șoldurile jos.',
    ],
  },
  {
    id: 'flotari-diamant',
    nume: 'Flotări diamant',
    categorie: 'piept',
    grupe: ['triceps', 'pectoral interior'],
    dificultate: 'mediu',
    echipament: 'greutate corporală',
    met: 4,
    caloriiPeMinut: 7,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'flotari-inclinate',
    nume: 'Flotări înclinate',
    categorie: 'piept',
    grupe: ['pectoral inferior', 'triceps'],
    dificultate: 'usor',
    echipament: 'greutate corporală',
    met: 3.5,
    caloriiPeMinut: 6,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'fluturari-gantere',
    nume: 'Fluturări cu gantere',
    categorie: 'piept',
    grupe: ['pectorali'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 4,
    caloriiPeMinut: 6,
    seriiDefault: 3,
    repetariDefault: 12,
    greseliComune: ['Îndoi prea mult coatele (devine împins)'],
  },
  {
    id: 'crossover-cablu',
    nume: 'Crossover la cablu',
    categorie: 'piept',
    grupe: ['pectorali'],
    dificultate: 'mediu',
    echipament: 'cablu',
    met: 4,
    caloriiPeMinut: 6,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'chest-press-masina',
    nume: 'Împins la piept la mașină',
    categorie: 'piept',
    grupe: ['pectorali', 'triceps'],
    dificultate: 'usor',
    echipament: 'mașină',
    met: 4,
    caloriiPeMinut: 6,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'pullover-gantera',
    nume: 'Pullover cu gantera',
    categorie: 'piept',
    grupe: ['pectorali', 'dorsali'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 4,
    caloriiPeMinut: 6,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'dips-piept',
    nume: 'Dips la paralele (piept)',
    categorie: 'piept',
    grupe: ['pectoral inferior', 'triceps'],
    dificultate: 'greu',
    echipament: 'paralele',
    met: 5,
    caloriiPeMinut: 8,
    seriiDefault: 3,
    repetariDefault: 10,
    masurare: {
      type: 'reps_weight',
      allowsWeight: true,
      weightOptional: true,
      defaultSets: 3,
      defaultReps: 10,
      defaultWeightKg: 0,
      unitLabel: 'Repetări',
      bodyweightFactor: 0.8,
    },
  },

  // ---- SPATE ----
  {
    id: 'tractiuni',
    nume: 'Tracțiuni',
    categorie: 'spate',
    grupe: ['dorsali', 'biceps'],
    dificultate: 'greu',
    echipament: 'bară fixă',
    met: 5,
    caloriiPeMinut: 9,
    seriiDefault: 4,
    repetariDefault: 8,
    descriere: 'Regele exercițiilor de spate.',
    instructiuni: [
      'Priză mai lată decât umerii.',
      'Trage bărbia peste bară.',
      'Coboară controlat, complet.',
    ],
    greseliComune: ['Balansezi corpul', 'Nu cobori complet'],
  },
  {
    id: 'tractiuni-priza-inversa',
    nume: 'Tracțiuni priză inversă (chin-ups)',
    categorie: 'spate',
    grupe: ['dorsali', 'biceps'],
    dificultate: 'greu',
    echipament: 'bară fixă',
    met: 5,
    caloriiPeMinut: 9,
    seriiDefault: 3,
    repetariDefault: 8,
  },
  {
    id: 'ramat-bara',
    nume: 'Ramat cu bara',
    categorie: 'spate',
    grupe: ['dorsali', 'romboizi', 'biceps'],
    dificultate: 'mediu',
    echipament: 'bară',
    met: 5,
    caloriiPeMinut: 8,
    seriiDefault: 4,
    repetariDefault: 10,
    instructiuni: [
      'Șold împins în spate, spate drept.',
      'Trage bara spre abdomenul inferior.',
      'Strânge omoplații.',
    ],
  },
  {
    id: 'ramat-gantera-un-brat',
    nume: 'Ramat cu gantera (un braț)',
    categorie: 'spate',
    grupe: ['dorsali', 'romboizi'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 4,
    caloriiPeMinut: 6,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'ramat-cablu-jos',
    nume: 'Ramat la cablu jos',
    categorie: 'spate',
    grupe: ['dorsali', 'trapez mijlociu'],
    dificultate: 'usor',
    echipament: 'cablu',
    met: 4,
    caloriiPeMinut: 6,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'lat-pulldown',
    nume: 'Tras la helcometru (lat pulldown)',
    categorie: 'spate',
    grupe: ['dorsali', 'biceps'],
    dificultate: 'usor',
    echipament: 'mașină',
    met: 4,
    caloriiPeMinut: 6,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'ramat-t-bar',
    nume: 'Ramat T-Bar',
    categorie: 'spate',
    grupe: ['dorsali', 'romboizi'],
    dificultate: 'mediu',
    echipament: 'bară',
    met: 5,
    caloriiPeMinut: 7,
    seriiDefault: 3,
    repetariDefault: 10,
  },
  {
    id: 'hiperextensii',
    nume: 'Hiperextensii lombare',
    categorie: 'spate',
    grupe: ['lombari', 'fesieri'],
    dificultate: 'usor',
    echipament: 'bancă romană',
    met: 3.5,
    caloriiPeMinut: 5,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'deadlift',
    nume: 'Îndreptări (deadlift)',
    categorie: 'spate',
    grupe: ['lombari', 'fesieri', 'femurali', 'trapez'],
    dificultate: 'greu',
    echipament: 'bară',
    met: 6,
    caloriiPeMinut: 9,
    seriiDefault: 4,
    repetariDefault: 6,
    descriere: 'Exercițiu compus full posterior.',
    instructiuni: [
      'Bara aproape de tibii.',
      'Spate neutru, piept sus.',
      'Împinge cu picioarele, extinde șoldul.',
    ],
    greseliComune: ['Rotunjești spatele', 'Ridici cu spatele nu cu picioarele'],
  },
  {
    id: 'ramat-masina',
    nume: 'Ramat la mașină',
    categorie: 'spate',
    grupe: ['dorsali', 'romboizi'],
    dificultate: 'usor',
    echipament: 'mașină',
    met: 4,
    caloriiPeMinut: 6,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'shrugs',
    nume: 'Ridicări de umeri (shrugs)',
    categorie: 'spate',
    grupe: ['trapez'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 3.5,
    caloriiPeMinut: 5,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'face-pull',
    nume: 'Face pull',
    categorie: 'spate',
    grupe: ['deltoid posterior', 'trapez'],
    dificultate: 'usor',
    echipament: 'cablu',
    met: 3.5,
    caloriiPeMinut: 5,
    seriiDefault: 3,
    repetariDefault: 15,
    sfaturi: ['Excelent pentru postură și sănătatea umerilor'],
  },

  // ---- PICIOARE ----
  {
    id: 'genuflexiuni-bara',
    nume: 'Genuflexiuni cu bara (squat)',
    categorie: 'picioare',
    grupe: ['cvadriceps', 'fesieri', 'femurali'],
    dificultate: 'greu',
    echipament: 'bară',
    met: 6,
    caloriiPeMinut: 9,
    seriiDefault: 4,
    repetariDefault: 8,
    descriere: 'Regele exercițiilor pentru picioare.',
    instructiuni: [
      'Bara pe trapez, picioarele la lățimea umerilor.',
      'Coboară până coapsele sunt paralele cu solul.',
      'Împinge prin călcâie.',
    ],
    greseliComune: ['Genunchii cad spre interior', 'Ridici călcâiele'],
  },
  {
    id: 'genuflexiuni-fata',
    nume: 'Genuflexiuni frontale (front squat)',
    categorie: 'picioare',
    grupe: ['cvadriceps', 'core'],
    dificultate: 'greu',
    echipament: 'bară',
    met: 6,
    caloriiPeMinut: 9,
    seriiDefault: 3,
    repetariDefault: 8,
  },
  {
    id: 'presa-picioare',
    nume: 'Presa de picioare',
    categorie: 'picioare',
    grupe: ['cvadriceps', 'fesieri'],
    dificultate: 'usor',
    echipament: 'mașină',
    met: 5,
    caloriiPeMinut: 7,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'fandari',
    nume: 'Fandări',
    categorie: 'picioare',
    grupe: ['cvadriceps', 'fesieri'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 5,
    caloriiPeMinut: 7,
    seriiDefault: 3,
    repetariDefault: 12,
    instructiuni: [
      'Pas mare în față.',
      'Coboară până genunchiul din spate aproape atinge solul.',
      'Împinge înapoi în poziția inițială.',
    ],
  },
  {
    id: 'fandari-mers',
    nume: 'Fandări în mers',
    categorie: 'picioare',
    grupe: ['cvadriceps', 'fesieri'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 5.5,
    caloriiPeMinut: 8,
    seriiDefault: 3,
    repetariDefault: 20,
  },
  {
    id: 'indreptari-romanesti',
    nume: 'Îndreptări românești (RDL)',
    categorie: 'picioare',
    grupe: ['femurali', 'fesieri'],
    dificultate: 'mediu',
    echipament: 'bară',
    met: 5,
    caloriiPeMinut: 7,
    seriiDefault: 3,
    repetariDefault: 10,
    greseliComune: ['Îndoi genunchii prea mult', 'Rotunjești spatele'],
  },
  {
    id: 'extensii-cvadriceps',
    nume: 'Extensii cvadriceps (leg extension)',
    categorie: 'picioare',
    grupe: ['cvadriceps'],
    dificultate: 'usor',
    echipament: 'mașină',
    met: 4,
    caloriiPeMinut: 5,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'flexii-femurali',
    nume: 'Flexii femurali (leg curl)',
    categorie: 'picioare',
    grupe: ['femurali'],
    dificultate: 'usor',
    echipament: 'mașină',
    met: 4,
    caloriiPeMinut: 5,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'ridicari-varfuri',
    nume: 'Ridicări pe vârfuri (calf raises)',
    categorie: 'picioare',
    grupe: ['gambe'],
    dificultate: 'usor',
    echipament: 'greutate corporală',
    met: 3.5,
    caloriiPeMinut: 4,
    seriiDefault: 4,
    repetariDefault: 20,
  },
  {
    id: 'genuflexiuni-bulgaresti',
    nume: 'Genuflexiuni bulgărești',
    categorie: 'picioare',
    grupe: ['cvadriceps', 'fesieri'],
    dificultate: 'greu',
    echipament: 'gantere',
    met: 5.5,
    caloriiPeMinut: 8,
    seriiDefault: 3,
    repetariDefault: 10,
  },
  {
    id: 'hip-thrust',
    nume: 'Hip thrust',
    categorie: 'picioare',
    grupe: ['fesieri', 'femurali'],
    dificultate: 'mediu',
    echipament: 'bară',
    met: 5,
    caloriiPeMinut: 7,
    seriiDefault: 4,
    repetariDefault: 10,
    sfaturi: ['Cel mai bun exercițiu pentru fesieri'],
  },
  {
    id: 'step-up',
    nume: 'Step-up pe bancă',
    categorie: 'picioare',
    grupe: ['cvadriceps', 'fesieri'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 5,
    caloriiPeMinut: 7,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'genuflexiuni-sumo',
    nume: 'Genuflexiuni sumo',
    categorie: 'picioare',
    grupe: ['adductori', 'fesieri', 'cvadriceps'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 5,
    caloriiPeMinut: 7,
    seriiDefault: 3,
    repetariDefault: 12,
  },

  // ---- UMERI ----
  {
    id: 'impins-umeri-bara',
    nume: 'Împins deasupra capului cu bara (OHP)',
    categorie: 'umeri',
    grupe: ['deltoizi', 'triceps'],
    dificultate: 'mediu',
    echipament: 'bară',
    met: 5,
    caloriiPeMinut: 7,
    seriiDefault: 4,
    repetariDefault: 8,
    instructiuni: [
      'Bara la nivelul claviculei.',
      'Împinge deasupra capului.',
      'Nu arcui spatele excesiv.',
    ],
  },
  {
    id: 'impins-umeri-gantere',
    nume: 'Împins cu gantere pentru umeri',
    categorie: 'umeri',
    grupe: ['deltoizi', 'triceps'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 4.5,
    caloriiPeMinut: 6,
    seriiDefault: 3,
    repetariDefault: 10,
  },
  {
    id: 'ridicari-laterale',
    nume: 'Ridicări laterale',
    categorie: 'umeri',
    grupe: ['deltoid lateral'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 3.5,
    caloriiPeMinut: 5,
    seriiDefault: 4,
    repetariDefault: 15,
    greseliComune: ['Folosești avânt', 'Ridici prea sus'],
  },
  {
    id: 'ridicari-frontale',
    nume: 'Ridicări frontale',
    categorie: 'umeri',
    grupe: ['deltoid anterior'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 3.5,
    caloriiPeMinut: 5,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'fluturari-spate',
    nume: 'Fluturări deltoid posterior (reverse fly)',
    categorie: 'umeri',
    grupe: ['deltoid posterior'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 3.5,
    caloriiPeMinut: 5,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'arnold-press',
    nume: 'Arnold Press',
    categorie: 'umeri',
    grupe: ['deltoizi'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 4.5,
    caloriiPeMinut: 6,
    seriiDefault: 3,
    repetariDefault: 10,
  },

  // ---- BRAȚE ----
  {
    id: 'flexii-biceps-bara',
    nume: 'Flexii biceps cu bara',
    categorie: 'brate',
    grupe: ['biceps'],
    dificultate: 'usor',
    echipament: 'bară',
    met: 3.5,
    caloriiPeMinut: 5,
    seriiDefault: 3,
    repetariDefault: 12,
    greseliComune: ['Balansezi corpul'],
  },
  {
    id: 'flexii-biceps-gantere',
    nume: 'Flexii biceps cu gantere',
    categorie: 'brate',
    grupe: ['biceps'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 3.5,
    caloriiPeMinut: 5,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'flexii-ciocan',
    nume: 'Flexii ciocan (hammer curl)',
    categorie: 'brate',
    grupe: ['biceps', 'brahial'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 3.5,
    caloriiPeMinut: 5,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'flexii-concentrate',
    nume: 'Flexii concentrate',
    categorie: 'brate',
    grupe: ['biceps'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 3,
    caloriiPeMinut: 4,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'extensii-triceps-cablu',
    nume: 'Extensii triceps la cablu',
    categorie: 'brate',
    grupe: ['triceps'],
    dificultate: 'usor',
    echipament: 'cablu',
    met: 3.5,
    caloriiPeMinut: 5,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'skullcrushers',
    nume: 'Extensii triceps la frunte (skullcrushers)',
    categorie: 'brate',
    grupe: ['triceps'],
    dificultate: 'mediu',
    echipament: 'bară EZ',
    met: 3.5,
    caloriiPeMinut: 5,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'dips-triceps-banca',
    nume: 'Dips triceps la bancă',
    categorie: 'brate',
    grupe: ['triceps'],
    dificultate: 'usor',
    echipament: 'bancă',
    met: 4,
    caloriiPeMinut: 6,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'kickback-triceps',
    nume: 'Kickback triceps',
    categorie: 'brate',
    grupe: ['triceps'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 3,
    caloriiPeMinut: 4,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'extensii-triceps-deasupra',
    nume: 'Extensii triceps deasupra capului',
    categorie: 'brate',
    grupe: ['triceps'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 3.5,
    caloriiPeMinut: 5,
    seriiDefault: 3,
    repetariDefault: 12,
  },

  // ---- ABDOMEN ----
  {
    id: 'abdomene-clasice',
    nume: 'Abdomene clasice (crunches)',
    categorie: 'abdomen',
    grupe: ['abdomeni'],
    dificultate: 'usor',
    echipament: 'greutate corporală',
    met: 3.5,
    caloriiPeMinut: 4,
    seriiDefault: 3,
    repetariDefault: 20,
  },
  {
    id: 'plank',
    nume: 'Planșă (plank)',
    categorie: 'abdomen',
    grupe: ['core', 'transvers abdominal'],
    dificultate: 'usor',
    echipament: 'greutate corporală',
    met: 3.5,
    caloriiPeMinut: 4,
    seriiDefault: 3,
    repetariDefault: 1,
    instructiuni: [
      'Cot sub umăr, corp drept.',
      'Strânge abdomenul și fesierii.',
      'Nu lăsa șoldurile jos.',
    ],
  },
  {
    id: 'ridicari-picioare-atarnat',
    nume: 'Ridicări de picioare atârnat',
    categorie: 'abdomen',
    grupe: ['abdomeni inferiori', 'flexori șold'],
    dificultate: 'greu',
    echipament: 'bară fixă',
    met: 4,
    caloriiPeMinut: 6,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'russian-twist',
    nume: 'Russian twist',
    categorie: 'abdomen',
    grupe: ['oblici'],
    dificultate: 'mediu',
    echipament: 'greutate corporală',
    met: 4,
    caloriiPeMinut: 6,
    seriiDefault: 3,
    repetariDefault: 20,
  },
  {
    id: 'mountain-climbers',
    nume: 'Mountain climbers',
    categorie: 'abdomen',
    grupe: ['core', 'cardio'],
    dificultate: 'mediu',
    echipament: 'greutate corporală',
    met: 8,
    caloriiPeMinut: 10,
    seriiDefault: 3,
    repetariDefault: 30,
  },
  {
    id: 'bicycle-crunch',
    nume: 'Bicycle crunch',
    categorie: 'abdomen',
    grupe: ['oblici', 'abdomeni'],
    dificultate: 'usor',
    echipament: 'greutate corporală',
    met: 4,
    caloriiPeMinut: 6,
    seriiDefault: 3,
    repetariDefault: 20,
  },
  {
    id: 'plank-lateral',
    nume: 'Planșă laterală',
    categorie: 'abdomen',
    grupe: ['oblici', 'core'],
    dificultate: 'mediu',
    echipament: 'greutate corporală',
    met: 3.5,
    caloriiPeMinut: 4,
    seriiDefault: 3,
    repetariDefault: 1,
  },
  {
    id: 'dead-bug',
    nume: 'Dead bug',
    categorie: 'abdomen',
    grupe: ['core'],
    dificultate: 'usor',
    echipament: 'greutate corporală',
    met: 3,
    caloriiPeMinut: 4,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'v-ups',
    nume: 'V-ups',
    categorie: 'abdomen',
    grupe: ['abdomeni', 'flexori șold'],
    dificultate: 'greu',
    echipament: 'greutate corporală',
    met: 4.5,
    caloriiPeMinut: 7,
    seriiDefault: 3,
    repetariDefault: 12,
  },

  // ---- CARDIO ----
  {
    id: 'alergare',
    nume: 'Alergare',
    categorie: 'cardio',
    grupe: ['picioare', 'cardio'],
    dificultate: 'mediu',
    echipament: 'niciunul',
    met: 9.8,
    caloriiPeMinut: 12,
    seriiDefault: 1,
    repetariDefault: 1,
    descriere: 'Cardio clasic pentru rezistență și ardere.',
  },
  {
    id: 'mers-rapid',
    nume: 'Mers alert',
    categorie: 'cardio',
    grupe: ['picioare', 'cardio'],
    dificultate: 'usor',
    echipament: 'niciunul',
    met: 4.3,
    caloriiPeMinut: 5,
    seriiDefault: 1,
    repetariDefault: 1,
  },
  {
    id: 'ciclism',
    nume: 'Ciclism',
    categorie: 'cardio',
    grupe: ['picioare', 'cardio'],
    dificultate: 'mediu',
    echipament: 'bicicletă',
    met: 7.5,
    caloriiPeMinut: 9,
    seriiDefault: 1,
    repetariDefault: 1,
  },
  {
    id: 'sarituri-coarda',
    nume: 'Sărituri cu coarda',
    categorie: 'cardio',
    grupe: ['full-body', 'cardio'],
    dificultate: 'mediu',
    echipament: 'coardă',
    met: 11,
    caloriiPeMinut: 13,
    seriiDefault: 3,
    repetariDefault: 50,
  },
  {
    id: 'burpees',
    nume: 'Burpees',
    categorie: 'cardio',
    grupe: ['full-body', 'cardio'],
    dificultate: 'greu',
    echipament: 'greutate corporală',
    met: 8,
    caloriiPeMinut: 11,
    seriiDefault: 3,
    repetariDefault: 12,
    greseliComune: ['Formă neglijentă când obosești'],
  },
  {
    id: 'jumping-jacks',
    nume: 'Jumping jacks',
    categorie: 'cardio',
    grupe: ['full-body', 'cardio'],
    dificultate: 'usor',
    echipament: 'greutate corporală',
    met: 8,
    caloriiPeMinut: 9,
    seriiDefault: 3,
    repetariDefault: 30,
  },
  {
    id: 'eliptic',
    nume: 'Eliptic',
    categorie: 'cardio',
    grupe: ['full-body', 'cardio'],
    dificultate: 'usor',
    echipament: 'mașină',
    met: 5,
    caloriiPeMinut: 7,
    seriiDefault: 1,
    repetariDefault: 1,
  },
  {
    id: 'vaslit',
    nume: 'Vâslit (rowing)',
    categorie: 'cardio',
    grupe: ['spate', 'picioare', 'cardio'],
    dificultate: 'mediu',
    echipament: 'mașină',
    met: 7,
    caloriiPeMinut: 9,
    seriiDefault: 1,
    repetariDefault: 1,
  },
  {
    id: 'urcat-scari',
    nume: 'Urcat scări (stairmaster)',
    categorie: 'cardio',
    grupe: ['picioare', 'cardio'],
    dificultate: 'mediu',
    echipament: 'mașină',
    met: 9,
    caloriiPeMinut: 11,
    seriiDefault: 1,
    repetariDefault: 1,
  },
  {
    id: 'high-knees',
    nume: 'Genunchi sus (high knees)',
    categorie: 'cardio',
    grupe: ['picioare', 'core', 'cardio'],
    dificultate: 'mediu',
    echipament: 'greutate corporală',
    met: 8,
    caloriiPeMinut: 10,
    seriiDefault: 3,
    repetariDefault: 30,
  },
  {
    id: 'sprint-intervale',
    nume: 'Sprinturi pe intervale (HIIT)',
    categorie: 'cardio',
    grupe: ['picioare', 'cardio'],
    dificultate: 'greu',
    echipament: 'niciunul',
    met: 12,
    caloriiPeMinut: 15,
    seriiDefault: 5,
    repetariDefault: 1,
  },

  // ---- FULL BODY ----
  {
    id: 'kettlebell-swing',
    nume: 'Kettlebell swing',
    categorie: 'full-body',
    grupe: ['fesieri', 'femurali', 'core', 'umeri'],
    dificultate: 'mediu',
    echipament: 'kettlebell',
    met: 9,
    caloriiPeMinut: 11,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'thruster',
    nume: 'Thruster',
    categorie: 'full-body',
    grupe: ['picioare', 'umeri', 'core'],
    dificultate: 'greu',
    echipament: 'bară',
    met: 8,
    caloriiPeMinut: 11,
    seriiDefault: 3,
    repetariDefault: 10,
  },
  {
    id: 'clean-and-press',
    nume: 'Clean and press',
    categorie: 'full-body',
    grupe: ['full-body'],
    dificultate: 'greu',
    echipament: 'bară',
    met: 8,
    caloriiPeMinut: 11,
    seriiDefault: 3,
    repetariDefault: 8,
  },
  {
    id: 'turkish-get-up',
    nume: 'Turkish get-up',
    categorie: 'full-body',
    grupe: ['core', 'umeri', 'picioare'],
    dificultate: 'greu',
    echipament: 'kettlebell',
    met: 6,
    caloriiPeMinut: 8,
    seriiDefault: 3,
    repetariDefault: 5,
  },
  {
    id: 'farmer-walk',
    nume: 'Farmer walk',
    categorie: 'full-body',
    grupe: ['prindere', 'trapez', 'core'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 6,
    caloriiPeMinut: 8,
    seriiDefault: 3,
    repetariDefault: 1,
  },
  {
    id: 'battle-ropes',
    nume: 'Battle ropes',
    categorie: 'full-body',
    grupe: ['umeri', 'brate', 'core', 'cardio'],
    dificultate: 'mediu',
    echipament: 'frânghii',
    met: 8,
    caloriiPeMinut: 10,
    seriiDefault: 4,
    repetariDefault: 1,
  },
  {
    id: 'bear-crawl',
    nume: 'Bear crawl',
    categorie: 'full-body',
    grupe: ['core', 'umeri', 'picioare'],
    dificultate: 'mediu',
    echipament: 'greutate corporală',
    met: 7,
    caloriiPeMinut: 9,
    seriiDefault: 3,
    repetariDefault: 1,
  },
  {
    id: 'genuflexiuni-cu-saritura',
    nume: 'Genuflexiuni cu săritură (jump squats)',
    categorie: 'full-body',
    grupe: ['picioare', 'cardio'],
    dificultate: 'mediu',
    echipament: 'greutate corporală',
    met: 8,
    caloriiPeMinut: 10,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'wall-balls',
    nume: 'Wall balls',
    categorie: 'full-body',
    grupe: ['picioare', 'umeri', 'core'],
    dificultate: 'mediu',
    echipament: 'minge medicinală',
    met: 8,
    caloriiPeMinut: 10,
    seriiDefault: 3,
    repetariDefault: 15,
  },

  // ---- MOBILITATE ----
  {
    id: 'stretching-femurali',
    nume: 'Stretching femurali',
    categorie: 'mobilitate',
    grupe: ['femurali'],
    dificultate: 'usor',
    echipament: 'niciunul',
    met: 2.3,
    caloriiPeMinut: 3,
    seriiDefault: 2,
    repetariDefault: 1,
  },
  {
    id: 'cat-cow',
    nume: 'Cat-cow (mobilitate coloană)',
    categorie: 'mobilitate',
    grupe: ['coloană', 'core'],
    dificultate: 'usor',
    echipament: 'niciunul',
    met: 2.3,
    caloriiPeMinut: 3,
    seriiDefault: 2,
    repetariDefault: 10,
  },
  {
    id: 'rotatii-solduri',
    nume: 'Rotații de șolduri',
    categorie: 'mobilitate',
    grupe: ['șolduri'],
    dificultate: 'usor',
    echipament: 'niciunul',
    met: 2.3,
    caloriiPeMinut: 3,
    seriiDefault: 2,
    repetariDefault: 10,
  },
  {
    id: 'foam-rolling',
    nume: 'Foam rolling',
    categorie: 'mobilitate',
    grupe: ['full-body'],
    dificultate: 'usor',
    echipament: 'foam roller',
    met: 2.5,
    caloriiPeMinut: 3,
    seriiDefault: 2,
    repetariDefault: 1,
  },
  {
    id: 'stretching-piept',
    nume: 'Stretching piept la perete',
    categorie: 'mobilitate',
    grupe: ['pectorali', 'umeri'],
    dificultate: 'usor',
    echipament: 'niciunul',
    met: 2.3,
    caloriiPeMinut: 3,
    seriiDefault: 2,
    repetariDefault: 1,
  },
];

import type { MuscleId } from '../components/fitness/heatColor';

export function deriveMuschiTinta(ex: Exercitiu): Partial<Record<MuscleId, number>> {
  if (ex.muschiTinta) {
    return ex.muschiTinta as Partial<Record<MuscleId, number>>;
  }
  const out: Partial<Record<MuscleId, number>> = {};
  const mapGroupToMuscleIds = (group: string): { id: MuscleId; pct: number }[] => {
    const g = group.toLowerCase().trim();
    if (/pectorali|piept|pectoral/i.test(g)) return [{ id: 'chest', pct: 100 }];
    if (/deltoid anterior|umeri anteriori/i.test(g)) return [{ id: 'delts', pct: 85 }];
    if (/deltoid lateral|umeri laterali/i.test(g)) return [{ id: 'delts', pct: 85 }];
    if (/deltoid posterior|umeri posteriori/i.test(g)) return [{ id: 'delts', pct: 80 }];
    if (/umeri|deltoizi/i.test(g)) return [{ id: 'delts', pct: 80 }];
    if (/biceps/i.test(g)) return [{ id: 'biceps', pct: 90 }];
    if (/triceps/i.test(g)) return [{ id: 'triceps', pct: 90 }];
    if (/antebrate|brahial|brate|brațe/i.test(g)) return [{ id: 'forearms', pct: 60 }];
    if (/abdomen|abdomeni|core/i.test(g)) return [{ id: 'abs', pct: 90 }];
    if (/oblici/i.test(g)) return [{ id: 'obliques', pct: 80 }];
    if (/trapez/i.test(g)) return [{ id: 'traps', pct: 80 }];
    if (/dorsali|spate/i.test(g)) return [{ id: 'lats', pct: 95 }];
    if (/lombari|coloană/i.test(g)) return [{ id: 'lower_back', pct: 75 }];
    // Romboizii nu au slot separat in desenul anatomic — se distribuie pe trapez.
    if (/romboizi/i.test(g)) return [{ id: 'traps', pct: 70 }];
    if (/fesieri|șolduri/i.test(g)) return [{ id: 'glutes', pct: 85 }];
    if (/cvadriceps|picioare/i.test(g)) return [{ id: 'quads', pct: 95 }];
    if (/ischiogambieri|femurali/i.test(g)) return [{ id: 'hamstrings', pct: 85 }];
    if (/gambe/i.test(g)) return [{ id: 'calves', pct: 75 }];
    // FIX HARTA: 'abductori' lipsea complet, iar regexul /adductori/ prindea si
    // "abductori" => muschiul abductor nu se aprindea NICIODATA, se colora adductorul.
    // Desenul nu are slot de abductori — se distribuie pe fesieri (zona soldului).
    if (/abductori|fesier mijlociu/i.test(g)) return [{ id: 'glutes', pct: 80 }];
    if (/adductori/i.test(g)) return [{ id: 'adductors', pct: 65 }];
    if (/full-body|corp_intreg|cardio/i.test(g)) return [
      { id: 'quads', pct: 60 },
      { id: 'chest', pct: 50 },
      { id: 'lats', pct: 50 },
      { id: 'abs', pct: 50 },
    ];
    return [];
  };

  ex.grupe.forEach((g, idx) => {
    const factor = idx === 0 ? 1.0 : idx === 1 ? 0.75 : 0.5;
    const mapped = mapGroupToMuscleIds(g);
    mapped.forEach(({ id, pct }) => {
      const value = Math.round(pct * factor);
      out[id] = Math.max(out[id] ?? 0, value);
    });
  });

  return out;
}

const TOATE_EXERCITIILE: Exercitiu[] = [
  ...EXERCITII,
  ...NEW_EXERCISES,
  ...NEW_EXERCISES_V2,
  ...NEW_EXERCISES_V3,
];

// FIX: catalogul e compus din 4 surse; fara deduplicare un id duplicat aparea de 2 ori
// in liste si era numarat dublu in statistici.
export const EXERCITII_DB: Exercitiu[] = TOATE_EXERCITIILE.filter(
  (e, i, arr) => arr.findIndex((x) => x.id === e.id) === i,
).map((e) => ({
  ...e,
  masurare: e.masurare ?? classifyMeasurement(e),
  muschiTinta: e.muschiTinta ?? deriveMuschiTinta(e),
}));

export const getExercitiuById = (id: string): Exercitiu | undefined =>
  EXERCITII_DB.find((e) => e.id === id);

export const getExercitiiByCategorie = (categorie: Categorie): Exercitiu[] =>
  EXERCITII_DB.filter((e) => e.categorie === categorie);
