/**
 * new_exercises_v2.ts — Extensie majoră de exerciții (v2)
 * Adaugă 50 de exerciții noi pentru toate grupele musculare, inclusiv:
 * - Antebrațe (5) — zonă anterior neacoperită
 * - Umeri (6) — variații suplimentare
 * - Core/Abdomen (6) — exerciții avansate
 * - Mobilitate/Stretching (6) — rutină completă
 * - Picioare (4), Spate (5), Piept (3), Brațe (5)
 * - Cardio (4), Full-body (4), Superior (1), Inferior (1), Core (1)
 * 
 * Total: 50 exerciții noi (155 total în EXERCITII_DB)
 */

import type { Exercitiu } from './exercitii';

export const NEW_EXERCISES_V2: Exercitiu[] = [

  // ══════════════════════════════════════════════
  // ANTEBRAȚE (5) — Anterior 0 exerciții dedicate
  // ══════════════════════════════════════════════

  {
    id: 'flexii-pumni-bara',
    nume: 'Flexii Pumni cu Bara (Wrist Curls)',
    categorie: 'brate',
    grupe: ['antebrate', 'brate'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 3.0,
    descriere: 'Stai pe bancă, antebrațele sprijinite pe coapse, palmele în sus. Rulează gantera doar din încheietură, fără a mișca brațul.',
    instructiuni: ['Așază-te pe bancă cu gantera în mână', 'Spijină antebrațul pe coapsă, cu palma în sus', 'Coboară gantera controlat, întinzând încheietura', 'Ridică doar din încheietură, contractând antebrațul', 'Controlează mișcarea pe tot parcursul'],
    seriiDefault: 3,
    repetariDefault: 15,
    muschiTinta: { antebrate: 100 },
    greseliComune: ['Mișcarea brațului în loc de încheietură', 'Greutate prea mare → formă incorectă'],
  },
  {
    id: 'extensii-pumni-bara',
    nume: 'Extensii Pumni cu Bara (Reverse Wrist Curls)',
    categorie: 'brate',
    grupe: ['antebrate', 'brate'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 3.0,
    descriere: 'Antebrațele sprijinite pe coapse, palmele în jos. Extinde gantera din încheietură.',
    instructiuni: ['Spijină antebrațul pe coapsă, palma în jos', 'Coboară gantera controlat', 'Ridică doar din încheietură, fără a mișca brațul'],
    seriiDefault: 3,
    repetariDefault: 15,
    muschiTinta: { antebrate: 100, brate: 30 },
  },
  {
    id: 'rulou-grip-bara',
    nume: 'Rulou Grip cu Bara (Barbell Finger Rolls)',
    categorie: 'brate',
    grupe: ['antebrate', 'brate'],
    dificultate: 'mediu',
    echipament: 'bara',
    met: 3.5,
    descriere: 'Ține bara cu palmele în sus, desfă degetele până bara ajunge la vârfuri, apoi strânge pumnii.',
    instructiuni: ['Stai drept, ține bara cu palmele în sus', 'Desfă degetele lent, lăsând bara să coboare', 'Strânge pumnii, ridicând bara doar din degete', 'Repetă ritmic'],
    seriiDefault: 3,
    repetariDefault: 20,
    muschiTinta: { antebrate: 100, brate: 20 },
  },
  {
    id: 'flexii-ciocan-gantera',
    nume: 'Flexii Ciocan cu Gantera (Hammer Curls)',
    categorie: 'brate',
    grupe: ['brate', 'biceps', 'antebrate'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 4.0,
    descriere: 'Ține ganterele cu palmele orientate spre corp (priză ciocan). Ridică alternativ, menținând încheieturile fixe.',
    instructiuni: ['Stai drept cu gantera în fiecare mână, palmele spre corp', 'Menține coatele fixe lângă corp', 'Ridică gantera până la umăr, fără a roti încheietura', 'Coboară controlat'],
    seriiDefault: 3,
    repetariDefault: 12,
    muschiTinta: { biceps: 70, antebrate: 50, brate: 40 },
  },
  {
    id: 'priza-placutelor',
    nume: 'Menținere Plăcuțe (Plate Pinch Hold)',
    categorie: 'brate',
    grupe: ['antebrate'],
    dificultate: 'mediu',
    echipament: 'greutati',
    met: 2.5,
    descriere: 'Prinde 2 plăcuțe de greutate între degete și menține cât mai mult. Excelent pentru forța de priză.',
    instructiuni: ['Alege 2 plăcuțe de 5-10kg', 'Prinde-le între degete și police', 'Menține brațul drept pe lângă corp', 'Ține 30-60 secunde, apoi schimbă mâna'],
    seriiDefault: 3,
    repetariDefault: 1,
    muschiTinta: { antebrate: 100 },
    masurare: { type: 'timed', allowsWeight: true, weightOptional: true, defaultSets: 3, defaultDurationSec: 45, unitLabel: 'sec' },
  },

  // ══════════════════════════════════════════════
  // UMERI (6) — Variații suplimentare
  // ══════════════════════════════════════════════

  {
    id: 'ridicari-laterale-inclinat',
    nume: 'Ridicări Laterale în Inclinat (Bent-Over Lateral Raises)',
    categorie: 'umeri',
    grupe: ['umeri', 'deltoid posterior', 'spate'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 4.0,
    descriere: 'Aplecat la 45°, cu spatele drept. Ridică ganterele lateral, contractând deltoizii posteriori.',
    instructiuni: ['Stai cu genunchii ușor flexați, aplecat la 45°', 'Ține ganterele sub piept, palmele orientate spre interior', 'Ridică brațele lateral până la nivelul umerilor', 'Menține 1 secundă sus, apoi coboară controlat'],
    seriiDefault: 3,
    repetariDefault: 12,
    muschiTinta: { deltoid_posterior: 85, trapez: 30, spate: 20 },
    greseliComune: ['Rotunjirea spatelui', 'Folosirea impulsului'],
  },
  {
    id: 'ridicari-frontale-bara',
    nume: 'Ridicări Frontale cu Bara (Barbell Front Raises)',
    categorie: 'umeri',
    grupe: ['umeri', 'deltoid anterior'],
    dificultate: 'mediu',
    echipament: 'bara',
    met: 4.5,
    descriere: 'Ține bara cu priză pronată. Ridică bara drept în față până la nivelul umerilor.',
    instructiuni: ['Stai drept, bara sprijinită pe coapse', 'Ridică bara drept în față, brațele aproape întinse', 'Oprește la nivelul umerilor', 'Coboară controlat'],
    seriiDefault: 3,
    repetariDefault: 10,
    muschiTinta: { deltoid_anterior: 90, pectorali: 20 },
  },
  {
    id: 'arnold-press-gantere',
    nume: 'Arnold Press cu Gantere',
    categorie: 'umeri',
    grupe: ['umeri', 'deltoid anterior', 'deltoid lateral'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 5.0,
    descriere: 'Varianta rotativă a împinsului de umeri. Pornești cu palmele spre tine și le rotești spre exterior pe măsură ce împingi.',
    instructiuni: ['Stai pe bancă, ganterele la nivelul pieptului, palmele spre tine', 'Împinge ganterele în sus, rotind palmele spre exterior', 'Blochează sus cu palmele în față', 'Inversează mișcarea la coborâre'],
    seriiDefault: 3,
    repetariDefault: 10,
    muschiTinta: { deltoid_anterior: 70, deltoid_lateral: 50, triceps: 20 },
  },
  {
    id: 'ridicari-laterale-cablu-un-brat',
    nume: 'Ridicări Laterale la Cablu (1 Braț)',
    categorie: 'umeri',
    grupe: ['umeri', 'deltoid lateral'],
    dificultate: 'usor',
    echipament: 'cablu',
    met: 4.0,
    descriere: 'Prinde mânerul cablului inferior cu o mână. Ridică brațul lateral, menținând tensiune constantă.',
    instructiuni: ['Reglează cablul la nivelul taliei', 'Prinde mânerul cu mâna opusă', 'Ridică brațul lateral până la nivelul umărului', 'Coboară lent, menținând tensiunea'],
    seriiDefault: 3,
    repetariDefault: 12,
    muschiTinta: { deltoid_lateral: 95 },
  },
  {
    id: 'presa-umeri-cu-bara-din-spate',
    nume: 'Presă Umeri cu Bara din Spate (Behind-Neck Press)',
    categorie: 'umeri',
    grupe: ['umeri', 'deltoid anterior', 'deltoid lateral', 'trapez'],
    dificultate: 'greu',
    echipament: 'bara',
    met: 5.5,
    descriere: 'AVANSAT: Bara pe trapez, împinge vertical. Necesită mobilitate bună a umerilor.',
    instructiuni: ['Așază bara pe trapez (nu pe gât!)', 'Apucă bara mai larg decât umerii', 'Împinge bara vertical deasupra capului', 'Coboară controlat până la trapez', 'Menține spatele drept pe toată durata'],
    seriiDefault: 3,
    repetariDefault: 8,
    muschiTinta: { deltoid_anterior: 70, deltoid_lateral: 40, trapez: 30, triceps: 15 },
    greseliComune: ['Coborârea prea jos → stres pe articulația umărului', 'Arcuirea spatelui'],
  },
  {
    id: 'presa-umeri-cu-gantere-asimetric',
    nume: 'Presă Umeri Alternativă cu Gantere',
    categorie: 'umeri',
    grupe: ['umeri', 'deltoid anterior', 'triceps'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 5.0,
    descriere: 'Împinge câte o ganteră pe rând, menținând cealaltă ganteră blocată sus. Crește timpul sub tensiune.',
    instructiuni: ['Stai pe bancă cu spătar, ganterele la nivelul umerilor', 'Împinge gantera dreaptă, mențin-o sus', 'Coboară gantera dreaptă în timp ce o împingi pe stânga', 'Alternează continuu'],
    seriiDefault: 3,
    repetariDefault: 10,
    muschiTinta: { deltoid_anterior: 80, triceps: 20 },
  },

  // ══════════════════════════════════════════════
  // CORE / ABDOMEN (6) — Exerciții avansate
  // ══════════════════════════════════════════════

  {
    id: 'hanging-leg-raise',
    nume: 'Ridicări Picioare la Bara Fixă (Hanging Leg Raises)',
    categorie: 'abdomen',
    grupe: ['abdomen', 'oblici', 'antebrate'],
    dificultate: 'greu',
    echipament: 'bara',
    met: 5.0,
    descriere: 'Atârnă de bara fixă. Ridică picioarele drepte până la 90° (sau mai sus pentru avansați).',
    instructiuni: ['Prinde bara cu palmele orientate în față', 'Menține picioarele drepte, apropiate', 'Ridică picioarele până la nivelul șoldurilor (sau mai sus)', 'Coboară controlat, fără balans'],
    seriiDefault: 3,
    repetariDefault: 10,
    muschiTinta: { abdomen: 90, oblici: 30, antebrate: 20 },
    greseliComune: ['Balansarea corpului', 'Picioarele îndoite în loc de drepte'],
  },
  {
    id: 'dragon-flag',
    nume: 'Dragon Flag',
    categorie: 'abdomen',
    grupe: ['abdomen', 'oblici', 'lombari'],
    dificultate: 'greu',
    echipament: 'banca',
    met: 6.0,
    descriere: 'AVANSAT: Culcat pe bancă, ții de margine deasupra capului. Ridici corpul drept, sprijinit doar pe umeri.',
    instructiuni: ['Culcă-te pe bancă, apucă marginea deasupra capului', 'Ridică picioarele și bazinul, menținând corpul drept', 'Coboară lent, fără a atinge banca', 'Menține tensiunea abdominală maximă'],
    seriiDefault: 3,
    repetariDefault: 5,
    muschiTinta: { abdomen: 100, oblici: 40, lombari: 20 },
  },
  {
    id: 'cable-woodchop',
    nume: 'Woodchop la Cablu (Cable Woodchop)',
    categorie: 'abdomen',
    grupe: ['abdomen', 'oblici'],
    dificultate: 'mediu',
    echipament: 'cablu',
    met: 4.5,
    descriere: 'Prinde mânerul cablului superior. Rotește trunchiul în jos și lateral, simulând tăierea lemnului.',
    instructiuni: ['Reglează cablul sus, prinde mânerul cu ambele mâini', 'Rotește trunchiul și brațele în jos spre genunchiul opus', 'Controlează întoarcerea', 'Execută ambele părți'],
    seriiDefault: 3,
    repetariDefault: 12,
    muschiTinta: { oblici: 80, abdomen: 40 },
  },
  {
    id: 'pallof-press',
    nume: 'Pallof Press la Cablu',
    categorie: 'core',
    grupe: ['abdomen', 'oblici'],
    dificultate: 'mediu',
    echipament: 'cablu',
    met: 3.5,
    descriere: 'Prinde mânerul cablului la nivelul pieptului. Împinge brațele în față, rezistând rotației. Excelent pentru stabilitatea core-ului.',
    instructiuni: ['Reglează cablul la nivelul pieptului, stai lateral', 'Prinde mânerul cu ambele mâini, ține-l la piept', 'Împinge brațele drept în față', 'Menține 2-3 secunde, revino controlat'],
    seriiDefault: 3,
    repetariDefault: 10,
    muschiTinta: { oblici: 70, abdomen: 50 },
  },
  {
    id: 'ab-wheel-rollout-genunchi',
    nume: 'Ab Wheel Rollout din Genunchi',
    categorie: 'abdomen',
    grupe: ['abdomen', 'oblici', 'lombari'],
    dificultate: 'mediu',
    echipament: 'roata-abdomen',
    met: 5.5,
    descriere: 'Din genunchi, rulează roata în față până când corpul e aproape paralel cu solul, apoi revino.',
    instructiuni: ['Îngenunchează, apucă roata cu ambele mâini', 'Rulează încet în față, menținând spatele ușor arcuit', 'Oprește-te înainte de a pierde tensiunea lombară', 'Trage înapoi folosind abdomenul (nu șoldurile)'],
    seriiDefault: 3,
    repetariDefault: 8,
    muschiTinta: { abdomen: 85, oblici: 25, lombari: 20 },
  },
  {
    id: 'dead-bug-avansat',
    nume: 'Dead Bug cu Gantera (Weighted Dead Bug)',
    categorie: 'core',
    grupe: ['abdomen', 'oblici'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 4.0,
    descriere: 'Culcat pe spate, brațele și picioarele ridicate. Ține o ganteră în mâini. Extinde alternativ brațul și piciorul opus.',
    instructiuni: ['Culcă-te, ține gantera deasupra pieptului, genunchii la 90°', 'Extinde brațul drept și piciorul stâng simultan', 'Revino la poziția inițială', 'Alternează părțile'],
    seriiDefault: 3,
    repetariDefault: 10,
    muschiTinta: { abdomen: 75, oblici: 30 },
  },

  // ══════════════════════════════════════════════
  // MOBILITATE / STRETCHING (6) — Rutină completă
  // ══════════════════════════════════════════════

  {
    id: 'worlds-greatest-stretch',
    nume: 'World\'s Greatest Stretch',
    categorie: 'mobilitate',
    grupe: ['corp_intreg', 'picioare', 'spate'],
    dificultate: 'usor',
    echipament: 'bodyweight',
    met: 3.0,
    descriere: 'Din plank, adu un picior lângă mână, rotește trunchiul spre genunchiul ridicat. Cel mai complet stretch dinamic.',
    instructiuni: ['Începe din poziția de flotare', 'Adu piciorul drept lângă mâna dreaptă', 'Rotește brațul drept spre tavan, urmărindu-l cu privirea', 'Revino și repetă cu stângul'],
    seriiDefault: 2,
    repetariDefault: 5,
    muschiTinta: { corp_intreg: 50, ischiogambieri: 30, spate: 20 },
    masurare: { type: 'reps', allowsWeight: false, weightOptional: true, defaultSets: 2, defaultReps: 5, unitLabel: 'rep' },
  },
  {
    id: 'couch-stretch',
    nume: 'Couch Stretch (Întindere Cvadriceps)',
    categorie: 'mobilitate',
    grupe: ['picioare', 'cvadriceps'],
    dificultate: 'usor',
    echipament: 'bodyweight',
    met: 2.0,
    descriere: 'Îngenunchează cu spatele la o canapea/perete. Sprijină vârful piciorului pe canapea și împinge șoldul în față.',
    instructiuni: ['Îngenunchează în fața unei canapele', 'Așază vârful piciorului pe canapea', 'Împinge șoldul în față până simți întinderea', 'Menține 30-60 secunde, schimbă piciorul'],
    seriiDefault: 2,
    repetariDefault: 1,
    muschiTinta: { cvadriceps: 80 },
    masurare: { type: 'timed', allowsWeight: false, weightOptional: true, defaultSets: 2, defaultDurationSec: 45, unitLabel: 'sec' },
  },
  {
    id: 'thread-the-needle',
    nume: 'Thread the Needle (Mobilitate Toracică)',
    categorie: 'mobilitate',
    grupe: ['spate', 'umeri', 'trapez'],
    dificultate: 'usor',
    echipament: 'bodyweight',
    met: 2.0,
    descriere: 'Din 4 labe, treci o mână pe sub corp, rotind trunchiul. Îmbunătățește mobilitatea coloanei toracice.',
    instructiuni: ['Poziție 4 labe', 'Treci mâna dreaptă pe sub brațul stâng, palma în sus', 'Rotește trunchiul, umărul drept spre sol', 'Menține 15-30 sec, repetă pe cealaltă parte'],
    seriiDefault: 2,
    repetariDefault: 3,
    muschiTinta: { spate: 40, trapez: 30, deltoid_posterior: 20 },
  },
  {
    id: 'pigeon-pose',
    nume: 'Pigeon Pose (Întindere Fesieri)',
    categorie: 'mobilitate',
    grupe: ['picioare', 'fesieri', 'ischiogambieri'],
    dificultate: 'usor',
    echipament: 'bodyweight',
    met: 2.5,
    descriere: 'Adu un genunchi în față, rotit extern, și întinde celălalt picior în spate. Apleacă-te în față pentru o întindere profundă a fesierilor.',
    instructiuni: ['Din 4 labe, adu genunchiul drept în față lângă mâna dreaptă', 'Întinde piciorul stâng în spate', 'Apleacă trunchiul în față peste genunchiul drept', 'Menține 30-60 sec, schimbă piciorul'],
    seriiDefault: 2,
    repetariDefault: 1,
    muschiTinta: { fesieri: 80, ischiogambieri: 30 },
    masurare: { type: 'timed', allowsWeight: false, weightOptional: true, defaultSets: 2, defaultDurationSec: 45, unitLabel: 'sec' },
  },
  {
    id: 'scorpion-stretch',
    nume: 'Scorpion Stretch (Mobilitate Lombară)',
    categorie: 'mobilitate',
    grupe: ['spate', 'lombari', 'oblici'],
    dificultate: 'usor',
    echipament: 'bodyweight',
    met: 2.5,
    descriere: 'Culcat pe burtă, brațele în cruce. Ridică un picior și du-l peste corp spre mâna opusă.',
    instructiuni: ['Culcă-te pe burtă, brațele întinse lateral', 'Ridică piciorul drept, îndoaie genunchiul', 'Du piciorul peste corp spre mâna stângă', 'Menține 15-20 sec, alternează'],
    seriiDefault: 2,
    repetariDefault: 3,
    muschiTinta: { lombari: 50, oblici: 30 },
  },
  {
    id: 'pancake-stretch',
    nume: 'Pancake Stretch (Deschidere Șolduri)',
    categorie: 'mobilitate',
    grupe: ['picioare', 'fesieri', 'adductori'],
    dificultate: 'mediu',
    echipament: 'bodyweight',
    met: 2.5,
    descriere: 'Așezat cu picioarele desfăcute larg. Apleacă trunchiul în față, menținând spatele drept.',
    instructiuni: ['Așază-te pe sol, desfă picioarele cât de larg poți', 'Menține spatele drept', 'Apleacă-te încet în față din șolduri', 'Ține 30-60 secunde'],
    seriiDefault: 2,
    repetariDefault: 1,
    muschiTinta: { adductori: 70, fesieri: 30, ischiogambieri: 20 },
    masurare: { type: 'timed', allowsWeight: false, weightOptional: true, defaultSets: 2, defaultDurationSec: 45, unitLabel: 'sec' },
  },

  // ══════════════════════════════════════════════
  // PICIOARE (5)
  // ══════════════════════════════════════════════

  {
    id: 'genuflexiuni-pistol-assistate',
    nume: 'Pistol Squats Asistate (TRX/Bancă)',
    categorie: 'picioare',
    grupe: ['picioare', 'cvadriceps', 'fesieri'],
    dificultate: 'mediu',
    echipament: 'bodyweight',
    met: 5.0,
    descriere: 'Genuflexiune pe un picior, ținându-te ușor de un suport. Progresie spre pistol squat liber.',
    instructiuni: ['Stai pe un picior, ține de un suport cu o mână', 'Coboară controlat pe piciorul de sprijin', 'Menține celălalt picior întins în față', 'Împinge în călcâi pentru a reveni'],
    seriiDefault: 3,
    repetariDefault: 8,
    muschiTinta: { cvadriceps: 70, fesieri: 40 },
  },
  {
    id: 'pod-fesieri-un-picior',
    nume: 'Pod Fesieri pe Un Picior (Single-Leg Glute Bridge)',
    categorie: 'picioare',
    grupe: ['picioare', 'fesieri', 'ischiogambieri'],
    dificultate: 'usor',
    echipament: 'bodyweight',
    met: 3.5,
    descriere: 'Culcat pe spate, un picior ridicat. Împinge din călcâiul piciorului de pe sol pentru a ridica șoldurile.',
    instructiuni: ['Culcă-te, genunchiul drept flectat, piciorul stâng ridicat', 'Împinge din călcâiul drept, ridică șoldurile', 'Menține 1-2 secunde sus', 'Coboară controlat'],
    seriiDefault: 3,
    repetariDefault: 12,
    muschiTinta: { fesieri: 80, ischiogambieri: 30 },
  },
  {
    id: 'genuflexiuni-split-bulgaresti-greutate',
    nume: 'Bulgarian Split Squats cu Gantere',
    categorie: 'picioare',
    grupe: ['picioare', 'cvadriceps', 'fesieri'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 5.5,
    descriere: 'Piciorul din spate pe o bancă. Ține gantere în mâini. Coboară până genunchiul din spate aproape atinge solul.',
    instructiuni: ['Așază vârful piciorului stâng pe o bancă în spate', 'Ține gantere în fiecare mână', 'Coboară până genunchiul stâng aproape atinge solul', 'Împinge în călcâiul drept pentru a reveni'],
    seriiDefault: 3,
    repetariDefault: 10,
    muschiTinta: { cvadriceps: 60, fesieri: 50 },
  },
  {
    id: 'ridicari-varfuri-pe-un-picior',
    nume: 'Ridicări pe Vârfuri pe Un Picior',
    categorie: 'picioare',
    grupe: ['picioare', 'gambe'],
    dificultate: 'usor',
    echipament: 'bodyweight',
    met: 3.0,
    descriere: 'Stai pe un picior pe o margine ridicată. Ridică-te pe vârf, apoi coboară sub nivelul marginii pentru întindere maximă.',
    instructiuni: ['Stai pe o treaptă/margine pe un picior', 'Ridică-te pe vârf cât de sus poți', 'Coboară lent sub nivelul treptei', 'Simte întinderea gambei'],
    seriiDefault: 3,
    repetariDefault: 15,
    muschiTinta: { gambe: 100 },
  },
  {
    id: 'fandari-laterale-greutate',
    nume: 'Fandări Laterale cu Gantera (Lateral Lunges)',
    categorie: 'inferior',
    grupe: ['picioare', 'cvadriceps', 'adductori', 'fesieri'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 5.0,
    descriere: 'Ține o ganteră la piept. Fă un pas lateral larg, îndoaie genunchiul, menținând celălalt picior drept.',
    instructiuni: ['Stai drept, gantera la piept', 'Pas larg lateral cu piciorul drept', 'Îndoaie genunchiul drept, șoldul în spate', 'Împinge în călcâiul drept pentru a reveni'],
    seriiDefault: 3,
    repetariDefault: 10,
    muschiTinta: { cvadriceps: 50, adductori: 40, fesieri: 30 },
  },

  // ══════════════════════════════════════════════
  // SPATE (5)
  // ══════════════════════════════════════════════

  {
    id: 'pullups-greutate-gantera',
    nume: 'Tracțiuni cu Gantera între Picioare',
    categorie: 'spate',
    grupe: ['spate', 'dorsali', 'biceps'],
    dificultate: 'greu',
    echipament: 'bara',
    met: 6.0,
    descriere: 'Tracțiuni clasice cu o ganteră prinsă între picioare pentru rezistență adițională.',
    instructiuni: ['Prinde gantera între coapse sau glezne', 'Execută tracțiunea normală, bărbia peste bară', 'Coboară controlat până la întinderea completă', 'Menține priza fermă'],
    seriiDefault: 3,
    repetariDefault: 6,
    muschiTinta: { dorsali: 80, biceps: 30 },
    greseliComune: ['Balansarea corpului', 'Gâtul întins în față'],
  },
  {
    id: 'ramat-bara-inclinat',
    nume: 'Ramat cu Bara la 45° (Pendlay Rows)',
    categorie: 'spate',
    grupe: ['spate', 'dorsali', 'lombari'],
    dificultate: 'mediu',
    echipament: 'bara',
    met: 5.5,
    descriere: 'Aplecat la ~90°, trage bara de la sol până la piept, apoi las-o să cadă controlat. Exploziv la urcare.',
    instructiuni: ['Poziție aplecată, spatele paralel cu solul', 'Apucă bara mai lat decât umerii', 'Trage exploziv până la stern', 'Coboară controlat până la sol'],
    seriiDefault: 4,
    repetariDefault: 8,
    muschiTinta: { dorsali: 85, lombari: 20, trapez: 15 },
  },
  {
    id: 'kroc-rows',
    nume: 'Kroc Rows (Ramat Greu cu Gantera)',
    categorie: 'spate',
    grupe: ['spate', 'dorsali', 'biceps', 'antebrate'],
    dificultate: 'greu',
    echipament: 'gantere',
    met: 6.0,
    descriere: 'Ramat cu o ganteră grea, cu balans controlat. Dezvoltă forță brută și priză.',
    instructiuni: ['Sprijină genunchiul și mâna pe bancă', 'Apucă o ganteră grea cu cealaltă mână', 'Trage exploziv până la șold', 'Permite un ușor balans controlat al trunchiului', 'Fă mai multe repetări decât crezi că poți'],
    seriiDefault: 3,
    repetariDefault: 15,
    muschiTinta: { dorsali: 80, biceps: 25, antebrate: 20 },
  },
  {
    id: 'pullover-bara-dreapta',
    nume: 'Pullover cu Bara Dreaptă (Straight-Arm Pulldown)',
    categorie: 'spate',
    grupe: ['spate', 'dorsali'],
    dificultate: 'mediu',
    echipament: 'cablu',
    met: 4.0,
    descriere: 'La cablu superior, brațele drepte. Trage bara în jos până la coapse, menținând brațele întinse.',
    instructiuni: ['Prinde bara dreaptă la cablul superior', 'Brațele întinse, aplecat ușor în față', 'Trage bara în jos până la coapse, fără a îndoi brațele', 'Revino controlat'],
    seriiDefault: 3,
    repetariDefault: 12,
    muschiTinta: { dorsali: 90 },
  },
  {
    id: 'inverted-row-greutate',
    nume: 'Inverted Rows cu Greutate pe Piept',
    categorie: 'spate',
    grupe: ['spate', 'dorsali', 'biceps'],
    dificultate: 'mediu',
    echipament: 'bara',
    met: 4.5,
    descriere: 'Sub o bară la nivelul taliei, trage pieptul spre bară cu o plăcuță pe piept.',
    instructiuni: ['Reglează bara la nivelul taliei (rack sau Smith)', 'Așază o plăcuță pe piept', 'Trage pieptul până la bară', 'Coboară controlat'],
    seriiDefault: 3,
    repetariDefault: 10,
    muschiTinta: { dorsali: 75, biceps: 25 },
  },

  // ══════════════════════════════════════════════
  // PIEPT (4)
  // ══════════════════════════════════════════════

  {
    id: 'flotari-decline-greutate',
    nume: 'Flotări Declin cu Plăcuță pe Spate',
    categorie: 'piept',
    grupe: ['piept', 'triceps', 'deltoid anterior'],
    dificultate: 'mediu',
    echipament: 'greutati',
    met: 5.5,
    descriere: 'Picioarele ridicate pe o bancă, o plăcuță pe spate. Flotări cu accent pe partea superioară a pieptului.',
    instructiuni: ['Așază picioarele pe o bancă', 'Pune o plăcuță pe spate (cere ajutor dacă e nevoie)', 'Coboară pieptul aproape de sol', 'Împinge exploziv în sus'],
    seriiDefault: 3,
    repetariDefault: 10,
    muschiTinta: { pectorali: 85, triceps: 30, deltoid_anterior: 15 },
  },
  {
    id: 'impins-inclinat-masina',
    nume: 'Împins Inclinat la Mașină (Incline Machine Press)',
    categorie: 'piept',
    grupe: ['piept', 'pectorali', 'triceps'],
    dificultate: 'usor',
    echipament: 'masina',
    met: 5.0,
    descriere: 'Mașină cu scaun reglabil la 30-45°. Împinge mânerele uniform, focalizând pe pieptul superior.',
    instructiuni: ['Reglează scaunul la 30-45°', 'Apucă mânerele, spatele lipit de spătar', 'Împinge uniform, fără a bloca coatele', 'Coboară controlat'],
    seriiDefault: 3,
    repetariDefault: 12,
    muschiTinta: { pectorali: 85, triceps: 20, deltoid_anterior: 10 },
  },
  {
    id: 'fluturari-pec-deck-invers',
    nume: 'Pec Deck Invers (Reverse Pec Deck)',
    categorie: 'superior',
    grupe: ['umeri', 'deltoid_posterior', 'spate'],
    dificultate: 'usor',
    echipament: 'masina',
    met: 4.0,
    descriere: 'La mașina pec deck, stai invers (cu pieptul spre spătar). Trage mânerele în spate, lucrând deltoizii posteriori.',
    instructiuni: ['Reglează scaunul la înălțimea umerilor', 'Stai cu pieptul spre spătar', 'Trage mânerele în spate, strângând omoplații', 'Revino controlat'],
    seriiDefault: 3,
    repetariDefault: 12,
    muschiTinta: { deltoid_posterior: 80, romboizi: 30 },
  },
  {
    id: 'impins-banda-elastica',
    nume: 'Împins cu Bandă Elastică (Band Chest Press)',
    categorie: 'piept',
    grupe: ['piept', 'pectorali', 'triceps'],
    dificultate: 'usor',
    echipament: 'benzi',
    met: 4.0,
    descriere: 'Ancorează banda elastică în spate, apucă mânerele și împinge în față. Rezistență variabilă.',
    instructiuni: ['Ancorează banda în spate (ușă, rack)', 'Apucă mânerele, un pas în față pentru tensiune', 'Împinge brațele în față, contractând pieptul', 'Revino controlat'],
    seriiDefault: 3,
    repetariDefault: 15,
    muschiTinta: { pectorali: 75, triceps: 25 },
  },

  // ══════════════════════════════════════════════
  // BRAȚE (5)
  // ══════════════════════════════════════════════

  {
    id: 'flexii-biceps-priza-inversa',
    nume: 'Flexii Biceps cu Priza Inversă (Reverse Curls)',
    categorie: 'brate',
    grupe: ['brate', 'biceps', 'antebrate'],
    dificultate: 'mediu',
    echipament: 'bara',
    met: 4.0,
    descriere: 'Ține bara cu palmele în jos (priză pronată). Ridică bara, menținând coatele fixe. Accent pe brahial.',
    instructiuni: ['Apucă bara cu palmele în jos, la lățimea umerilor', 'Menține coatele lipite de corp', 'Ridică bara până la nivelul pieptului superior', 'Coboară controlat'],
    seriiDefault: 3,
    repetariDefault: 12,
    muschiTinta: { biceps: 50, antebrate: 50, brate: 30 },
  },
  {
    id: 'triceps-pushdown-funie-extensie',
    nume: 'Triceps Pushdown cu Funie (Rope Pushdown)',
    categorie: 'brate',
    grupe: ['brate', 'triceps'],
    dificultate: 'usor',
    echipament: 'cablu',
    met: 4.0,
    descriere: 'La cablu superior, prinde funia. Împinge în jos și desfă brațele lateral la final pentru contracție maximă.',
    instructiuni: ['Prinde funia la cablul superior', 'Coatele lipite de corp', 'Împinge în jos, la final desfă ușor brațele', 'Revino controlat, menținând coatele fixe'],
    seriiDefault: 3,
    repetariDefault: 12,
    muschiTinta: { triceps: 95 },
  },
  {
    id: 'french-press-gantere-un-brat',
    nume: 'French Press cu Gantera (1 Braț)',
    categorie: 'brate',
    grupe: ['brate', 'triceps'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 4.0,
    descriere: 'Stând sau pe bancă, ține o ganteră deasupra capului. Coboară gantera în spatele capului, apoi extinde.',
    instructiuni: ['Ține gantera deasupra capului, brațul drept', 'Coboară gantera în spatele capului, cotul sus', 'Extinde brațul înapoi sus', 'Menține cotul fix pe tot parcursul'],
    seriiDefault: 3,
    repetariDefault: 10,
    muschiTinta: { triceps: 100 },
  },
  {
    id: 'concetration-curl-avansat',
    nume: 'Concentration Curl cu Izometrie (3-Sec Pause)',
    categorie: 'brate',
    grupe: ['brate', 'biceps'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 3.5,
    descriere: 'Concentration curl cu pauză de 3 secunde în poziția de vârf. Maximizează timpul sub tensiune.',
    instructiuni: ['Așază-te, cotul sprijinit pe coapsă', 'Ridică gantera, contractând bicepsul', 'Menține 3 secunde în poziția de vârf', 'Coboară lent (3 secunde)'],
    seriiDefault: 3,
    repetariDefault: 8,
    muschiTinta: { biceps: 100 },
  },
  {
    id: 'dips-banca-greutate',
    nume: 'Dips pe Bancă cu Greutate în Poală',
    categorie: 'brate',
    grupe: ['brate', 'triceps', 'piept'],
    dificultate: 'mediu',
    echipament: 'greutati',
    met: 5.0,
    descriere: 'Dips pe două bănci, cu o plăcuță pe coapse. Coboară până simți întinderea în piept.',
    instructiuni: ['Două bănci paralele, mâinile pe una, călcâiele pe cealaltă', 'Așază o plăcuță pe coapse', 'Coboară până brațele sunt la 90°', 'Împinge în sus'],
    seriiDefault: 3,
    repetariDefault: 10,
    muschiTinta: { triceps: 70, pectorali: 30 },
  },

  // ══════════════════════════════════════════════
  // CARDIO (4)
  // ══════════════════════════════════════════════

  {
    id: 'sarituri-cutie',
    nume: 'Sărituri pe Cutie (Box Jumps)',
    categorie: 'cardio',
    grupe: ['picioare', 'cvadriceps', 'fesieri'],
    dificultate: 'mediu',
    echipament: 'cutie',
    met: 8.0,
    descriere: 'Sari pe o cutie/platformă de 50-75cm. Aterizează moale, cu genunchii ușor flexați.',
    instructiuni: ['Stai la 30cm de cutie, picioarele la lățimea umerilor', 'Balancează brațele și sari exploziv', 'Aterizează cu genunchii ușor flexați', 'Coboară de pe cutie și repetă'],
    seriiDefault: 3,
    repetariDefault: 10,
    muschiTinta: { cvadriceps: 60, fesieri: 40, gambe: 20 },
    greseliComune: ['Aterizarea cu picioarele drepte', 'Cutia prea înaltă pentru nivelul tău'],
  },
  {
    id: 'skater-jumps',
    nume: 'Skater Jumps (Sărituri Patinator)',
    categorie: 'cardio',
    grupe: ['picioare', 'cvadriceps', 'fesieri'],
    dificultate: 'mediu',
    echipament: 'bodyweight',
    met: 7.0,
    descriere: 'Sari lateral de pe un picior pe altul, aterizând controlat. Imită mișcarea unui patinator.',
    instructiuni: ['Stai pe piciorul drept, ușor flexat', 'Sari lateral pe piciorul stâng, aterizând moale', 'Brațele se mișcă natural pentru echilibru', 'Alternează continuu, ritm alert'],
    seriiDefault: 3,
    repetariDefault: 20,
    muschiTinta: { cvadriceps: 50, fesieri: 40, adductori: 20 },
  },
  {
    id: 'burpees-greutate',
    nume: 'Burpees cu Gantere (Dumbbell Burpees)',
    categorie: 'cardio',
    grupe: ['corp_intreg', 'picioare', 'piept'],
    dificultate: 'greu',
    echipament: 'gantere',
    met: 9.0,
    descriere: 'Burpee clasic ținând gantere în mâini. La săritură, împingi ganterele deasupra capului.',
    instructiuni: ['Ține gantere ușoare în mâini', 'Ghemuiește, pune ganterele pe sol', 'Sari înapoi în plank, fă o flotare', 'Sari înapoi, ridică-te și împinge ganterele deasupra capului'],
    seriiDefault: 3,
    repetariDefault: 8,
    muschiTinta: { corp_intreg: 70, cvadriceps: 40, pectorali: 20 },
  },
  {
    id: 'battle-ropes-alternativ',
    nume: 'Battle Ropes Alternativ (Valuri Alternante)',
    categorie: 'cardio',
    grupe: ['umeri', 'brate', 'abdomen'],
    dificultate: 'mediu',
    echipament: 'funii',
    met: 8.0,
    descriere: 'Prinde funiile, genunchii ușor flexați. Creează valuri alternante rapide, menținând ritmul constant.',
    instructiuni: ['Prinde capetele funiilor, stai cu genunchii ușor flexați', 'Generează valuri rapide, alternând brațele', 'Menține abdomenul încordat, spatele drept', 'Ritm alert pentru 30-45 secunde'],
    seriiDefault: 3,
    repetariDefault: 1,
    muschiTinta: { umeri: 40, brate: 30, abdomen: 20 },
    masurare: { type: 'timed', allowsWeight: false, weightOptional: true, defaultSets: 3, defaultDurationSec: 30, unitLabel: 'sec' },
  },

  // ══════════════════════════════════════════════
  // FULL-BODY (4)
  // ══════════════════════════════════════════════

  {
    id: 'kettlebell-snatch',
    nume: 'Kettlebell Snatch (Smuls cu Kettlebell)',
    categorie: 'full-body',
    grupe: ['corp_intreg', 'fesieri', 'umeri', 'spate'],
    dificultate: 'greu',
    echipament: 'kettlebell',
    met: 9.0,
    descriere: 'Mișcare balistică: dintr-un swing, trage kettlebell-ul deasupra capului într-o singură mișcare fluidă.',
    instructiuni: ['Pornește dintr-un swing cu un braț', 'Când kettlebell-ul ajunge la nivelul pieptului, trage-l vertical', 'Prinde kettlebell-ul deasupra capului cu brațul blocat', 'Coboară controlat și repetă'],
    seriiDefault: 3,
    repetariDefault: 8,
    muschiTinta: { fesieri: 50, deltoid_anterior: 30, dorsali: 20 },
  },
  {
    id: 'clean-gantera',
    nume: 'Clean cu Gantera (Dumbbell Clean)',
    categorie: 'full-body',
    grupe: ['corp_intreg', 'picioare', 'umeri', 'spate'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 7.0,
    descriere: 'Ridică ganterele de la sol până la umeri într-o mișcare explozivă, menținând spatele drept.',
    instructiuni: ['Ganterele pe sol între picioare', 'Apucă-le, spatele drept', 'Trage exploziv, ducând ganterele la umeri', 'Coboară controlat și repetă'],
    seriiDefault: 3,
    repetariDefault: 8,
    muschiTinta: { cvadriceps: 40, fesieri: 30, deltoid_anterior: 20, dorsali: 15 },
  },
  {
    id: 'sandbag-carry',
    nume: 'Sandbag Carry (Cărat Sac de Nisip)',
    categorie: 'full-body',
    grupe: ['corp_intreg', 'abdomen', 'antebrate', 'picioare'],
    dificultate: 'mediu',
    echipament: 'greutati',
    met: 6.0,
    descriere: 'Ține un sac de nisip (sau o ganteră grea) pe piept sau pe un umăr. Mergi 20-30m, menținând postura.',
    instructiuni: ['Ridică sacul/gantera grea', 'Ține-l pe piept sau pe umăr', 'Mergi 20-30 metri cu pași controlați', 'Menține abdomenul încordat, spatele drept'],
    seriiDefault: 3,
    repetariDefault: 1,
    muschiTinta: { abdomen: 40, antebrate: 30, cvadriceps: 20 },
    masurare: { type: 'timed', allowsWeight: true, weightOptional: false, defaultSets: 3, defaultDurationSec: 30, defaultWeightKg: 20, unitLabel: 'sec' },
  },
  {
    id: 'thruster-greutate',
    nume: 'Thruster cu Gantere (Dumbbell Thruster)',
    categorie: 'full-body',
    grupe: ['corp_intreg', 'cvadriceps', 'fesieri', 'umeri'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 8.0,
    descriere: 'O genuflexiune urmată de o presă de umeri într-o singură mișcare. Genuflexiunea oferă impuls pentru presă.',
    instructiuni: ['Ține ganterele la nivelul umerilor', 'Coboară în genuflexiune', 'Explodează în sus, împingând ganterele deasupra capului', 'Coboară ganterele și repetă fluid'],
    seriiDefault: 3,
    repetariDefault: 10,
    muschiTinta: { cvadriceps: 50, fesieri: 30, deltoid_anterior: 30 },
  },

];
