import type { Exercitiu } from './exercitii';

/**
 * NEW_EXERCISES_V3 — extindere catalog (audit 31.07.2026)
 *
 * Scop: acoperirea grupelor musculare care nu erau atinse de niciun exercitiu si
 * care rămâneau permanent "reci" pe harta corporală: deltoid posterior, romboizi,
 * antebrate, oblici, lombari, abductori, adductori, gambe.
 *
 * Denumirile din `grupe` folosesc exclusiv chei recunoscute de mapToCanonicalMuscleIds,
 * deci fiecare exercitiu contribuie corect la heatmap si la muscle_load.
 */
export const NEW_EXERCISES_V3: Exercitiu[] = [
  {
    id: 'face-pull-la-cablu',
    nume: 'Face pull la cablu',
    categorie: 'umeri',
    grupe: ['deltoid posterior', 'trapez', 'romboizi'],
    dificultate: 'mediu',
    echipament: 'cablu',
    met: 4.5,
    caloriiPeMinut: 5.0,
    seriiDefault: 4,
    repetariDefault: 15,
  },
  {
    id: 'face-pull-cu-banda-elastica',
    nume: 'Face pull cu banda elastica',
    categorie: 'umeri',
    grupe: ['deltoid posterior', 'romboizi'],
    dificultate: 'usor',
    echipament: 'banda elastica',
    met: 3.8,
    caloriiPeMinut: 4.2,
    seriiDefault: 3,
    repetariDefault: 18,
  },
  {
    id: 'fluturari-inverse-cu-gantere-aplecat',
    nume: 'Fluturari inverse cu gantere aplecat',
    categorie: 'umeri',
    grupe: ['deltoid posterior', 'romboizi', 'trapez'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 4.2,
    caloriiPeMinut: 4.6,
    seriiDefault: 4,
    repetariDefault: 14,
  },
  {
    id: 'fluturari-inverse-la-aparat-reverse-pec-deck',
    nume: 'Fluturari inverse la aparat (reverse pec deck)',
    categorie: 'umeri',
    grupe: ['deltoid posterior', 'romboizi'],
    dificultate: 'usor',
    echipament: 'aparat',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 4,
    repetariDefault: 15,
  },
  {
    id: 'fluturari-inverse-la-cablu-incrucisat',
    nume: 'Fluturari inverse la cablu incrucisat',
    categorie: 'umeri',
    grupe: ['deltoid posterior', 'trapez'],
    dificultate: 'mediu',
    echipament: 'cablu',
    met: 4.2,
    caloriiPeMinut: 4.6,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'ramat-cu-priza-larga-la-bara-rear-delt-row',
    nume: 'Ramat cu priza larga la bara (rear delt row)',
    categorie: 'spate',
    grupe: ['deltoid posterior', 'romboizi', 'dorsali'],
    dificultate: 'mediu',
    echipament: 'bara',
    met: 5.0,
    caloriiPeMinut: 5.5,
    seriiDefault: 4,
    repetariDefault: 12,
  },
  {
    id: 'ridicari-in-y-la-banca-inclinata',
    nume: 'Ridicari in Y la banca inclinata',
    categorie: 'umeri',
    grupe: ['deltoid posterior', 'romboizi', 'trapez'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 3.5,
    caloriiPeMinut: 3.9,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'ridicari-in-t-la-banca-inclinata',
    nume: 'Ridicari in T la banca inclinata',
    categorie: 'spate',
    grupe: ['romboizi', 'deltoid posterior', 'trapez'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 3.5,
    caloriiPeMinut: 3.9,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'ridicari-in-w-la-banca-inclinata',
    nume: 'Ridicari in W la banca inclinata',
    categorie: 'spate',
    grupe: ['romboizi', 'trapez', 'deltoid posterior'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 3.5,
    caloriiPeMinut: 3.9,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'retractii-scapulare-la-bara-fixa',
    nume: 'Retractii scapulare la bara fixa',
    categorie: 'spate',
    grupe: ['romboizi', 'trapez', 'dorsali'],
    dificultate: 'usor',
    echipament: 'bara fixa',
    met: 3.5,
    caloriiPeMinut: 3.9,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'ramat-cu-banda-elastica-sezand',
    nume: 'Ramat cu banda elastica sezand',
    categorie: 'spate',
    grupe: ['romboizi', 'dorsali', 'trapez'],
    dificultate: 'usor',
    echipament: 'banda elastica',
    met: 3.8,
    caloriiPeMinut: 4.2,
    seriiDefault: 3,
    repetariDefault: 18,
  },
  {
    id: 'prone-snow-angel',
    nume: 'Prone snow angel',
    categorie: 'spate',
    grupe: ['romboizi', 'deltoid posterior', 'trapez'],
    dificultate: 'usor',
    echipament: 'greutate corporala',
    met: 3.0,
    caloriiPeMinut: 3.3,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'band-pull-apart',
    nume: 'Band pull-apart',
    categorie: 'umeri',
    grupe: ['deltoid posterior', 'romboizi'],
    dificultate: 'usor',
    echipament: 'banda elastica',
    met: 3.2,
    caloriiPeMinut: 3.5,
    seriiDefault: 3,
    repetariDefault: 20,
  },
  {
    id: 'flexii-de-incheietura-cu-bara',
    nume: 'Flexii de incheietura cu bara',
    categorie: 'brate',
    grupe: ['antebrate'],
    dificultate: 'usor',
    echipament: 'bara',
    met: 3.0,
    caloriiPeMinut: 3.3,
    seriiDefault: 4,
    repetariDefault: 15,
  },
  {
    id: 'extensii-de-incheietura-cu-bara',
    nume: 'Extensii de incheietura cu bara',
    categorie: 'brate',
    grupe: ['antebrate'],
    dificultate: 'usor',
    echipament: 'bara',
    met: 3.0,
    caloriiPeMinut: 3.3,
    seriiDefault: 4,
    repetariDefault: 15,
  },
  {
    id: 'flexii-de-incheietura-cu-gantera-pe-banca',
    nume: 'Flexii de incheietura cu gantera pe banca',
    categorie: 'brate',
    grupe: ['antebrate'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 3.0,
    caloriiPeMinut: 3.3,
    seriiDefault: 3,
    repetariDefault: 18,
  },
  {
    id: 'flexii-inverse-cu-bara-reverse-curl',
    nume: 'Flexii inverse cu bara (reverse curl)',
    categorie: 'brate',
    grupe: ['antebrate', 'biceps'],
    dificultate: 'mediu',
    echipament: 'bara',
    met: 3.5,
    caloriiPeMinut: 3.9,
    seriiDefault: 4,
    repetariDefault: 12,
  },
  {
    id: 'flexii-hammer-cu-gantere',
    nume: 'Flexii Hammer cu gantere',
    categorie: 'brate',
    grupe: ['biceps', 'antebrate'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 3.5,
    caloriiPeMinut: 3.9,
    seriiDefault: 4,
    repetariDefault: 12,
  },
  {
    id: 'farmer-carry-mers-cu-greutati',
    nume: 'Farmer carry (mers cu greutati)',
    categorie: 'full-body',
    grupe: ['antebrate', 'trapez', 'abdomen'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 5.5,
    caloriiPeMinut: 6.1,
    seriiDefault: 4,
    repetariDefault: 1,
  },
  {
    id: 'suspendare-pasiva-in-bara-dead-hang',
    nume: 'Suspendare pasiva in bara (dead hang)',
    categorie: 'spate',
    grupe: ['antebrate', 'dorsali', 'trapez'],
    dificultate: 'usor',
    echipament: 'bara fixa',
    met: 3.5,
    caloriiPeMinut: 3.9,
    seriiDefault: 4,
    repetariDefault: 1,
  },
  {
    id: 'strangere-de-gripper',
    nume: 'Strangere de gripper',
    categorie: 'brate',
    grupe: ['antebrate'],
    dificultate: 'usor',
    echipament: 'gripper',
    met: 2.8,
    caloriiPeMinut: 3.1,
    seriiDefault: 4,
    repetariDefault: 20,
  },
  {
    id: 'rulare-de-prosop-cu-greutate',
    nume: 'Rulare de prosop cu greutate',
    categorie: 'brate',
    grupe: ['antebrate'],
    dificultate: 'mediu',
    echipament: 'greutate',
    met: 3.2,
    caloriiPeMinut: 3.5,
    seriiDefault: 3,
    repetariDefault: 10,
  },
  {
    id: 'plate-pinch-prindere-de-disc',
    nume: 'Plate pinch (prindere de disc)',
    categorie: 'brate',
    grupe: ['antebrate'],
    dificultate: 'mediu',
    echipament: 'disc',
    met: 3.0,
    caloriiPeMinut: 3.3,
    seriiDefault: 4,
    repetariDefault: 1,
  },
  {
    id: 'plank-lateral-v3',
    nume: 'Plank lateral',
    categorie: 'abdomen',
    grupe: ['oblici', 'abdomen'],
    dificultate: 'usor',
    echipament: 'greutate corporala',
    met: 3.5,
    caloriiPeMinut: 3.9,
    seriiDefault: 3,
    repetariDefault: 1,
  },
  {
    id: 'plank-lateral-cu-ridicare-de-bazin',
    nume: 'Plank lateral cu ridicare de bazin',
    categorie: 'abdomen',
    grupe: ['oblici', 'abdomen'],
    dificultate: 'mediu',
    echipament: 'greutate corporala',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'rotiri-rusesti-cu-minge-medicinala',
    nume: 'Rotiri rusesti cu minge medicinala',
    categorie: 'abdomen',
    grupe: ['oblici', 'abdomen'],
    dificultate: 'mediu',
    echipament: 'minge medicinala',
    met: 4.5,
    caloriiPeMinut: 5.0,
    seriiDefault: 3,
    repetariDefault: 20,
  },
  {
    id: 'pallof-press-la-cablu',
    nume: 'Pallof press la cablu',
    categorie: 'abdomen',
    grupe: ['oblici', 'abdomen'],
    dificultate: 'mediu',
    echipament: 'cablu',
    met: 3.8,
    caloriiPeMinut: 4.2,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'woodchopper-de-sus-in-jos-la-cablu',
    nume: 'Woodchopper de sus in jos la cablu',
    categorie: 'abdomen',
    grupe: ['oblici', 'abdomen'],
    dificultate: 'mediu',
    echipament: 'cablu',
    met: 4.5,
    caloriiPeMinut: 5.0,
    seriiDefault: 3,
    repetariDefault: 14,
  },
  {
    id: 'woodchopper-de-jos-in-sus-la-cablu',
    nume: 'Woodchopper de jos in sus la cablu',
    categorie: 'abdomen',
    grupe: ['oblici', 'abdomen'],
    dificultate: 'mediu',
    echipament: 'cablu',
    met: 4.5,
    caloriiPeMinut: 5.0,
    seriiDefault: 3,
    repetariDefault: 14,
  },
  {
    id: 'inclinari-laterale-cu-gantera',
    nume: 'Inclinari laterale cu gantera',
    categorie: 'abdomen',
    grupe: ['oblici'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 3.2,
    caloriiPeMinut: 3.5,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'suitcase-carry',
    nume: 'Suitcase carry',
    categorie: 'full-body',
    grupe: ['oblici', 'antebrate', 'abdomen'],
    dificultate: 'mediu',
    echipament: 'gantera',
    met: 5.0,
    caloriiPeMinut: 5.5,
    seriiDefault: 3,
    repetariDefault: 1,
  },
  {
    id: 'bicycle-crunch-v3',
    nume: 'Bicycle crunch',
    categorie: 'abdomen',
    grupe: ['oblici', 'abdomen'],
    dificultate: 'usor',
    echipament: 'greutate corporala',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 3,
    repetariDefault: 20,
  },
  {
    id: 'windshield-wipers',
    nume: 'Windshield wipers',
    categorie: 'abdomen',
    grupe: ['oblici', 'abdomen'],
    dificultate: 'greu',
    echipament: 'greutate corporala',
    met: 4.5,
    caloriiPeMinut: 5.0,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'heel-taps-laterale',
    nume: 'Heel taps laterale',
    categorie: 'abdomen',
    grupe: ['oblici'],
    dificultate: 'usor',
    echipament: 'greutate corporala',
    met: 3.0,
    caloriiPeMinut: 3.3,
    seriiDefault: 3,
    repetariDefault: 20,
  },
  {
    id: 'copenhagen-plank',
    nume: 'Copenhagen plank',
    categorie: 'picioare',
    grupe: ['adductori', 'oblici'],
    dificultate: 'greu',
    echipament: 'greutate corporala',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 3,
    repetariDefault: 1,
  },
  {
    id: 'extensii-lombare-la-banca-romana',
    nume: 'Extensii lombare la banca romana',
    categorie: 'spate',
    grupe: ['lombari', 'fesieri', 'ischiogambieri'],
    dificultate: 'usor',
    echipament: 'banca romana',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'reverse-hyperextension',
    nume: 'Reverse hyperextension',
    categorie: 'spate',
    grupe: ['lombari', 'fesieri'],
    dificultate: 'mediu',
    echipament: 'aparat',
    met: 4.2,
    caloriiPeMinut: 4.6,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'good-morning-cu-bara',
    nume: 'Good morning cu bara',
    categorie: 'picioare',
    grupe: ['lombari', 'ischiogambieri', 'fesieri'],
    dificultate: 'greu',
    echipament: 'bara',
    met: 5.0,
    caloriiPeMinut: 5.5,
    seriiDefault: 4,
    repetariDefault: 10,
  },
  {
    id: 'superman',
    nume: 'Superman',
    categorie: 'spate',
    grupe: ['lombari', 'fesieri'],
    dificultate: 'usor',
    echipament: 'greutate corporala',
    met: 3.0,
    caloriiPeMinut: 3.3,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'bird-dog',
    nume: 'Bird dog',
    categorie: 'abdomen',
    grupe: ['lombari', 'abdomen', 'fesieri'],
    dificultate: 'usor',
    echipament: 'greutate corporala',
    met: 3.0,
    caloriiPeMinut: 3.3,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'jefferson-curl',
    nume: 'Jefferson curl',
    categorie: 'mobilitate',
    grupe: ['lombari', 'ischiogambieri'],
    dificultate: 'greu',
    echipament: 'gantera',
    met: 3.0,
    caloriiPeMinut: 3.3,
    seriiDefault: 3,
    repetariDefault: 8,
  },
  {
    id: 'indreptari-romanesti-cu-gantere',
    nume: 'Indreptari romanesti cu gantere',
    categorie: 'picioare',
    grupe: ['ischiogambieri', 'fesieri', 'lombari'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 5.0,
    caloriiPeMinut: 5.5,
    seriiDefault: 4,
    repetariDefault: 10,
  },
  {
    id: 'indreptari-cu-picioare-drepte-la-bara',
    nume: 'Indreptari cu picioare drepte la bara',
    categorie: 'picioare',
    grupe: ['ischiogambieri', 'lombari', 'fesieri'],
    dificultate: 'greu',
    echipament: 'bara',
    met: 5.5,
    caloriiPeMinut: 6.1,
    seriiDefault: 4,
    repetariDefault: 8,
  },
  {
    id: 'abductii-de-coapsa-la-aparat',
    nume: 'Abductii de coapsa la aparat',
    categorie: 'picioare',
    grupe: ['abductori', 'fesieri'],
    dificultate: 'usor',
    echipament: 'aparat',
    met: 3.8,
    caloriiPeMinut: 4.2,
    seriiDefault: 4,
    repetariDefault: 15,
  },
  {
    id: 'abductii-la-cablu-in-stand',
    nume: 'Abductii la cablu in stand',
    categorie: 'picioare',
    grupe: ['abductori', 'fesieri'],
    dificultate: 'usor',
    echipament: 'cablu',
    met: 3.8,
    caloriiPeMinut: 4.2,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'mers-lateral-cu-banda-lateral-band-walk',
    nume: 'Mers lateral cu banda (lateral band walk)',
    categorie: 'picioare',
    grupe: ['abductori', 'fesieri'],
    dificultate: 'usor',
    echipament: 'banda elastica',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 3,
    repetariDefault: 20,
  },
  {
    id: 'ridicari-laterale-de-picior-culcat',
    nume: 'Ridicari laterale de picior culcat',
    categorie: 'picioare',
    grupe: ['abductori', 'fesieri'],
    dificultate: 'usor',
    echipament: 'greutate corporala',
    met: 3.2,
    caloriiPeMinut: 3.5,
    seriiDefault: 3,
    repetariDefault: 18,
  },
  {
    id: 'clamshell-cu-banda',
    nume: 'Clamshell cu banda',
    categorie: 'picioare',
    grupe: ['abductori', 'fesieri'],
    dificultate: 'usor',
    echipament: 'banda elastica',
    met: 3.0,
    caloriiPeMinut: 3.3,
    seriiDefault: 3,
    repetariDefault: 20,
  },
  {
    id: 'monster-walk-cu-banda',
    nume: 'Monster walk cu banda',
    categorie: 'picioare',
    grupe: ['abductori', 'fesieri', 'cvadriceps'],
    dificultate: 'mediu',
    echipament: 'banda elastica',
    met: 4.2,
    caloriiPeMinut: 4.6,
    seriiDefault: 3,
    repetariDefault: 20,
  },
  {
    id: 'adductii-de-coapsa-la-aparat',
    nume: 'Adductii de coapsa la aparat',
    categorie: 'picioare',
    grupe: ['adductori'],
    dificultate: 'usor',
    echipament: 'aparat',
    met: 3.8,
    caloriiPeMinut: 4.2,
    seriiDefault: 4,
    repetariDefault: 15,
  },
  {
    id: 'genuflexiuni-sumo-cu-gantera',
    nume: 'Genuflexiuni sumo cu gantera',
    categorie: 'picioare',
    grupe: ['adductori', 'cvadriceps', 'fesieri'],
    dificultate: 'mediu',
    echipament: 'gantera',
    met: 5.5,
    caloriiPeMinut: 6.1,
    seriiDefault: 4,
    repetariDefault: 12,
  },
  {
    id: 'cossack-squat',
    nume: 'Cossack squat',
    categorie: 'picioare',
    grupe: ['adductori', 'cvadriceps', 'fesieri'],
    dificultate: 'greu',
    echipament: 'greutate corporala',
    met: 5.0,
    caloriiPeMinut: 5.5,
    seriiDefault: 3,
    repetariDefault: 10,
  },
  {
    id: 'fandari-laterale',
    nume: 'Fandari laterale',
    categorie: 'picioare',
    grupe: ['adductori', 'cvadriceps', 'fesieri'],
    dificultate: 'mediu',
    echipament: 'greutate corporala',
    met: 4.8,
    caloriiPeMinut: 5.3,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'adductii-la-cablu',
    nume: 'Adductii la cablu',
    categorie: 'picioare',
    grupe: ['adductori'],
    dificultate: 'usor',
    echipament: 'cablu',
    met: 3.5,
    caloriiPeMinut: 3.9,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'ridicari-pe-varfuri-in-stand-cu-bara',
    nume: 'Ridicari pe varfuri in stand cu bara',
    categorie: 'picioare',
    grupe: ['gambe'],
    dificultate: 'mediu',
    echipament: 'bara',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 4,
    repetariDefault: 15,
  },
  {
    id: 'ridicari-pe-varfuri-la-aparat-sezand',
    nume: 'Ridicari pe varfuri la aparat sezand',
    categorie: 'picioare',
    grupe: ['gambe'],
    dificultate: 'usor',
    echipament: 'aparat',
    met: 3.8,
    caloriiPeMinut: 4.2,
    seriiDefault: 4,
    repetariDefault: 18,
  },
  {
    id: 'ridicari-pe-varfuri-pe-un-picior',
    nume: 'Ridicari pe varfuri pe un picior',
    categorie: 'picioare',
    grupe: ['gambe'],
    dificultate: 'mediu',
    echipament: 'greutate corporala',
    met: 3.8,
    caloriiPeMinut: 4.2,
    seriiDefault: 3,
    repetariDefault: 20,
  },
  {
    id: 'donkey-calf-raise',
    nume: 'Donkey calf raise',
    categorie: 'picioare',
    grupe: ['gambe'],
    dificultate: 'mediu',
    echipament: 'aparat',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 4,
    repetariDefault: 15,
  },
  {
    id: 'ridicari-pe-varfuri-la-presa-de-picioare',
    nume: 'Ridicari pe varfuri la presa de picioare',
    categorie: 'picioare',
    grupe: ['gambe'],
    dificultate: 'usor',
    echipament: 'aparat',
    met: 3.8,
    caloriiPeMinut: 4.2,
    seriiDefault: 4,
    repetariDefault: 18,
  },
  {
    id: 'ridicari-de-tibial-tibialis-raise',
    nume: 'Ridicari de tibial (tibialis raise)',
    categorie: 'picioare',
    grupe: ['gambe'],
    dificultate: 'usor',
    echipament: 'greutate corporala',
    met: 3.0,
    caloriiPeMinut: 3.3,
    seriiDefault: 3,
    repetariDefault: 20,
  },
  {
    id: 'sarituri-pe-varfuri-pogo-hops',
    nume: 'Sarituri pe varfuri (pogo hops)',
    categorie: 'cardio',
    grupe: ['gambe', 'cardio'],
    dificultate: 'mediu',
    echipament: 'greutate corporala',
    met: 8.0,
    caloriiPeMinut: 8.8,
    seriiDefault: 3,
    repetariDefault: 30,
  },
  {
    id: 'impins-la-piept-cu-gantere-inclinat',
    nume: 'Impins la piept cu gantere inclinat',
    categorie: 'piept',
    grupe: ['pectorali', 'deltoid anterior', 'triceps'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 5.0,
    caloriiPeMinut: 5.5,
    seriiDefault: 4,
    repetariDefault: 10,
  },
  {
    id: 'impins-la-piept-cu-gantere-declinat',
    nume: 'Impins la piept cu gantere declinat',
    categorie: 'piept',
    grupe: ['pectorali', 'triceps'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 5.0,
    caloriiPeMinut: 5.5,
    seriiDefault: 4,
    repetariDefault: 10,
  },
  {
    id: 'impins-la-aparat-smith-inclinat',
    nume: 'Impins la aparat Smith inclinat',
    categorie: 'piept',
    grupe: ['pectorali', 'deltoid anterior'],
    dificultate: 'usor',
    echipament: 'aparat',
    met: 4.5,
    caloriiPeMinut: 5.0,
    seriiDefault: 4,
    repetariDefault: 12,
  },
  {
    id: 'fluturari-la-cablu-de-sus-high-to-low',
    nume: 'Fluturari la cablu de sus (high to low)',
    categorie: 'piept',
    grupe: ['pectorali'],
    dificultate: 'mediu',
    echipament: 'cablu',
    met: 4.2,
    caloriiPeMinut: 4.6,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'fluturari-la-cablu-de-jos-low-to-high',
    nume: 'Fluturari la cablu de jos (low to high)',
    categorie: 'piept',
    grupe: ['pectorali', 'deltoid anterior'],
    dificultate: 'mediu',
    echipament: 'cablu',
    met: 4.2,
    caloriiPeMinut: 4.6,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'fluturari-la-pec-deck',
    nume: 'Fluturari la pec deck',
    categorie: 'piept',
    grupe: ['pectorali'],
    dificultate: 'usor',
    echipament: 'aparat',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 4,
    repetariDefault: 14,
  },
  {
    id: 'flotari-cu-priza-larga',
    nume: 'Flotari cu priza larga',
    categorie: 'piept',
    grupe: ['pectorali', 'triceps', 'deltoid anterior'],
    dificultate: 'usor',
    echipament: 'greutate corporala',
    met: 4.5,
    caloriiPeMinut: 5.0,
    seriiDefault: 4,
    repetariDefault: 15,
  },
  {
    id: 'flotari-cu-picioarele-ridicate',
    nume: 'Flotari cu picioarele ridicate',
    categorie: 'piept',
    grupe: ['pectorali', 'deltoid anterior', 'triceps'],
    dificultate: 'mediu',
    echipament: 'greutate corporala',
    met: 5.0,
    caloriiPeMinut: 5.5,
    seriiDefault: 4,
    repetariDefault: 12,
  },
  {
    id: 'flotari-cu-banda-elastica',
    nume: 'Flotari cu banda elastica',
    categorie: 'piept',
    grupe: ['pectorali', 'triceps'],
    dificultate: 'mediu',
    echipament: 'banda elastica',
    met: 4.8,
    caloriiPeMinut: 5.3,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'flotari-arceuate-archer-push-up',
    nume: 'Flotari arceuate (archer push-up)',
    categorie: 'piept',
    grupe: ['pectorali', 'triceps'],
    dificultate: 'greu',
    echipament: 'greutate corporala',
    met: 5.5,
    caloriiPeMinut: 6.1,
    seriiDefault: 3,
    repetariDefault: 10,
  },
  {
    id: 'pullover-cu-gantera',
    nume: 'Pullover cu gantera',
    categorie: 'piept',
    grupe: ['pectorali', 'dorsali'],
    dificultate: 'mediu',
    echipament: 'gantera',
    met: 4.5,
    caloriiPeMinut: 5.0,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'svend-press',
    nume: 'Svend press',
    categorie: 'piept',
    grupe: ['pectorali'],
    dificultate: 'usor',
    echipament: 'disc',
    met: 3.5,
    caloriiPeMinut: 3.9,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'paloane-la-paralele-aplecat-chest-dip',
    nume: 'Paloane la paralele aplecat (chest dip)',
    categorie: 'piept',
    grupe: ['pectorali', 'triceps'],
    dificultate: 'greu',
    echipament: 'paralele',
    met: 6.0,
    caloriiPeMinut: 6.6,
    seriiDefault: 4,
    repetariDefault: 10,
  },
  {
    id: 'tractiuni-cu-priza-larga',
    nume: 'Tractiuni cu priza larga',
    categorie: 'spate',
    grupe: ['dorsali', 'biceps', 'trapez'],
    dificultate: 'greu',
    echipament: 'bara fixa',
    met: 6.0,
    caloriiPeMinut: 6.6,
    seriiDefault: 4,
    repetariDefault: 8,
  },
  {
    id: 'tractiuni-cu-priza-inversa',
    nume: 'Tractiuni cu priza inversa',
    categorie: 'spate',
    grupe: ['dorsali', 'biceps'],
    dificultate: 'greu',
    echipament: 'bara fixa',
    met: 6.0,
    caloriiPeMinut: 6.6,
    seriiDefault: 4,
    repetariDefault: 8,
  },
  {
    id: 'tractiuni-neutre-la-maner-paralel',
    nume: 'Tractiuni neutre la maner paralel',
    categorie: 'spate',
    grupe: ['dorsali', 'biceps', 'romboizi'],
    dificultate: 'mediu',
    echipament: 'bara fixa',
    met: 5.8,
    caloriiPeMinut: 6.4,
    seriiDefault: 4,
    repetariDefault: 8,
  },
  {
    id: 'ramat-cu-gantera-pe-banca',
    nume: 'Ramat cu gantera pe banca',
    categorie: 'spate',
    grupe: ['dorsali', 'romboizi', 'biceps'],
    dificultate: 'mediu',
    echipament: 'gantera',
    met: 5.0,
    caloriiPeMinut: 5.5,
    seriiDefault: 4,
    repetariDefault: 10,
  },
  {
    id: 'ramat-t-bar-v3',
    nume: 'Ramat T-bar',
    categorie: 'spate',
    grupe: ['dorsali', 'romboizi', 'trapez'],
    dificultate: 'mediu',
    echipament: 'bara',
    met: 5.5,
    caloriiPeMinut: 6.1,
    seriiDefault: 4,
    repetariDefault: 10,
  },
  {
    id: 'ramat-la-cablu-sezand-cu-priza-larga',
    nume: 'Ramat la cablu sezand cu priza larga',
    categorie: 'spate',
    grupe: ['dorsali', 'romboizi'],
    dificultate: 'usor',
    echipament: 'cablu',
    met: 4.5,
    caloriiPeMinut: 5.0,
    seriiDefault: 4,
    repetariDefault: 12,
  },
  {
    id: 'ramat-pendlay',
    nume: 'Ramat Pendlay',
    categorie: 'spate',
    grupe: ['dorsali', 'lombari', 'trapez'],
    dificultate: 'greu',
    echipament: 'bara',
    met: 6.0,
    caloriiPeMinut: 6.6,
    seriiDefault: 4,
    repetariDefault: 8,
  },
  {
    id: 'ramat-meadows',
    nume: 'Ramat Meadows',
    categorie: 'spate',
    grupe: ['dorsali', 'trapez', 'romboizi'],
    dificultate: 'greu',
    echipament: 'bara',
    met: 5.5,
    caloriiPeMinut: 6.1,
    seriiDefault: 3,
    repetariDefault: 10,
  },
  {
    id: 'tras-la-helcometru-cu-priza-inversa',
    nume: 'Tras la helcometru cu priza inversa',
    categorie: 'spate',
    grupe: ['dorsali', 'biceps'],
    dificultate: 'usor',
    echipament: 'aparat',
    met: 4.5,
    caloriiPeMinut: 5.0,
    seriiDefault: 4,
    repetariDefault: 12,
  },
  {
    id: 'straight-arm-pulldown',
    nume: 'Straight-arm pulldown',
    categorie: 'spate',
    grupe: ['dorsali'],
    dificultate: 'usor',
    echipament: 'cablu',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'ramat-la-aparat-cu-suport-pentru-piept',
    nume: 'Ramat la aparat cu suport pentru piept',
    categorie: 'spate',
    grupe: ['dorsali', 'romboizi', 'trapez'],
    dificultate: 'usor',
    echipament: 'aparat',
    met: 4.5,
    caloriiPeMinut: 5.0,
    seriiDefault: 4,
    repetariDefault: 12,
  },
  {
    id: 'ridicari-de-umeri-cu-bara-shrug',
    nume: 'Ridicari de umeri cu bara (shrug)',
    categorie: 'spate',
    grupe: ['trapez'],
    dificultate: 'usor',
    echipament: 'bara',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 4,
    repetariDefault: 15,
  },
  {
    id: 'ridicari-de-umeri-cu-gantere',
    nume: 'Ridicari de umeri cu gantere',
    categorie: 'spate',
    grupe: ['trapez'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 4,
    repetariDefault: 15,
  },
  {
    id: 'ramat-vertical-la-bara-upright-row',
    nume: 'Ramat vertical la bara (upright row)',
    categorie: 'umeri',
    grupe: ['trapez', 'deltoid lateral'],
    dificultate: 'mediu',
    echipament: 'bara',
    met: 4.5,
    caloriiPeMinut: 5.0,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'impins-militar-cu-bara-in-stand',
    nume: 'Impins militar cu bara in stand',
    categorie: 'umeri',
    grupe: ['deltoid anterior', 'deltoid lateral', 'triceps'],
    dificultate: 'greu',
    echipament: 'bara',
    met: 5.5,
    caloriiPeMinut: 6.1,
    seriiDefault: 4,
    repetariDefault: 8,
  },
  {
    id: 'impins-cu-gantere-sezand',
    nume: 'Impins cu gantere sezand',
    categorie: 'umeri',
    grupe: ['deltoid anterior', 'deltoid lateral', 'triceps'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 5.0,
    caloriiPeMinut: 5.5,
    seriiDefault: 4,
    repetariDefault: 10,
  },
  {
    id: 'impins-arnold',
    nume: 'Impins Arnold',
    categorie: 'umeri',
    grupe: ['deltoid anterior', 'deltoid lateral'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 5.0,
    caloriiPeMinut: 5.5,
    seriiDefault: 4,
    repetariDefault: 10,
  },
  {
    id: 'ridicari-laterale-cu-gantere',
    nume: 'Ridicari laterale cu gantere',
    categorie: 'umeri',
    grupe: ['deltoid lateral'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 4,
    repetariDefault: 15,
  },
  {
    id: 'ridicari-laterale-la-cablu',
    nume: 'Ridicari laterale la cablu',
    categorie: 'umeri',
    grupe: ['deltoid lateral'],
    dificultate: 'usor',
    echipament: 'cablu',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'ridicari-laterale-la-aparat',
    nume: 'Ridicari laterale la aparat',
    categorie: 'umeri',
    grupe: ['deltoid lateral'],
    dificultate: 'usor',
    echipament: 'aparat',
    met: 3.8,
    caloriiPeMinut: 4.2,
    seriiDefault: 4,
    repetariDefault: 15,
  },
  {
    id: 'ridicari-frontale-cu-disc',
    nume: 'Ridicari frontale cu disc',
    categorie: 'umeri',
    grupe: ['deltoid anterior'],
    dificultate: 'usor',
    echipament: 'disc',
    met: 3.8,
    caloriiPeMinut: 4.2,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'ridicari-frontale-cu-gantere-alternativ',
    nume: 'Ridicari frontale cu gantere alternativ',
    categorie: 'umeri',
    grupe: ['deltoid anterior'],
    dificultate: 'usor',
    echipament: 'gantere',
    met: 3.8,
    caloriiPeMinut: 4.2,
    seriiDefault: 3,
    repetariDefault: 14,
  },
  {
    id: 'impins-landmine-cu-o-mana',
    nume: 'Impins landmine cu o mana',
    categorie: 'umeri',
    grupe: ['deltoid anterior', 'abdomen', 'triceps'],
    dificultate: 'mediu',
    echipament: 'bara',
    met: 5.0,
    caloriiPeMinut: 5.5,
    seriiDefault: 3,
    repetariDefault: 10,
  },
  {
    id: 'handstand-push-up-la-perete',
    nume: 'Handstand push-up la perete',
    categorie: 'umeri',
    grupe: ['deltoid anterior', 'triceps', 'trapez'],
    dificultate: 'greu',
    echipament: 'greutate corporala',
    met: 6.5,
    caloriiPeMinut: 7.2,
    seriiDefault: 3,
    repetariDefault: 6,
  },
  {
    id: 'pike-push-up',
    nume: 'Pike push-up',
    categorie: 'umeri',
    grupe: ['deltoid anterior', 'triceps'],
    dificultate: 'mediu',
    echipament: 'greutate corporala',
    met: 5.0,
    caloriiPeMinut: 5.5,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'flexii-cu-bara-ez',
    nume: 'Flexii cu bara EZ',
    categorie: 'brate',
    grupe: ['biceps', 'antebrate'],
    dificultate: 'usor',
    echipament: 'bara EZ',
    met: 3.8,
    caloriiPeMinut: 4.2,
    seriiDefault: 4,
    repetariDefault: 12,
  },
  {
    id: 'flexii-concentrate-cu-gantera',
    nume: 'Flexii concentrate cu gantera',
    categorie: 'brate',
    grupe: ['biceps'],
    dificultate: 'usor',
    echipament: 'gantera',
    met: 3.5,
    caloriiPeMinut: 3.9,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'flexii-la-banca-scott-preacher-curl',
    nume: 'Flexii la banca Scott (preacher curl)',
    categorie: 'brate',
    grupe: ['biceps'],
    dificultate: 'mediu',
    echipament: 'banca Scott',
    met: 3.8,
    caloriiPeMinut: 4.2,
    seriiDefault: 4,
    repetariDefault: 10,
  },
  {
    id: 'flexii-incline-cu-gantere',
    nume: 'Flexii incline cu gantere',
    categorie: 'brate',
    grupe: ['biceps'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 3.8,
    caloriiPeMinut: 4.2,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'flexii-la-cablu-de-jos',
    nume: 'Flexii la cablu de jos',
    categorie: 'brate',
    grupe: ['biceps'],
    dificultate: 'usor',
    echipament: 'cablu',
    met: 3.5,
    caloriiPeMinut: 3.9,
    seriiDefault: 4,
    repetariDefault: 12,
  },
  {
    id: 'flexii-spider-v3',
    nume: 'Flexii Spider',
    categorie: 'brate',
    grupe: ['biceps'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 3.8,
    caloriiPeMinut: 4.2,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'extensii-franceze-cu-bara-ez',
    nume: 'Extensii franceze cu bara EZ',
    categorie: 'brate',
    grupe: ['triceps'],
    dificultate: 'mediu',
    echipament: 'bara EZ',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 4,
    repetariDefault: 12,
  },
  {
    id: 'extensii-deasupra-capului-la-cablu',
    nume: 'Extensii deasupra capului la cablu',
    categorie: 'brate',
    grupe: ['triceps'],
    dificultate: 'usor',
    echipament: 'cablu',
    met: 3.8,
    caloriiPeMinut: 4.2,
    seriiDefault: 3,
    repetariDefault: 14,
  },
  {
    id: 'extensii-la-cablu-cu-frenghie',
    nume: 'Extensii la cablu cu frenghie',
    categorie: 'brate',
    grupe: ['triceps'],
    dificultate: 'usor',
    echipament: 'cablu',
    met: 3.8,
    caloriiPeMinut: 4.2,
    seriiDefault: 4,
    repetariDefault: 14,
  },
  {
    id: 'kickback-cu-gantera',
    nume: 'Kickback cu gantera',
    categorie: 'brate',
    grupe: ['triceps'],
    dificultate: 'usor',
    echipament: 'gantera',
    met: 3.2,
    caloriiPeMinut: 3.5,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'flotari-diamant-v3',
    nume: 'Flotari diamant',
    categorie: 'brate',
    grupe: ['triceps', 'pectorali'],
    dificultate: 'mediu',
    echipament: 'greutate corporala',
    met: 5.0,
    caloriiPeMinut: 5.5,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'paloane-la-banca-bench-dip',
    nume: 'Paloane la banca (bench dip)',
    categorie: 'brate',
    grupe: ['triceps', 'deltoid anterior'],
    dificultate: 'usor',
    echipament: 'banca',
    met: 4.5,
    caloriiPeMinut: 5.0,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'impins-in-priza-strimta-la-bara',
    nume: 'Impins in priza strimta la bara',
    categorie: 'brate',
    grupe: ['triceps', 'pectorali'],
    dificultate: 'mediu',
    echipament: 'bara',
    met: 5.0,
    caloriiPeMinut: 5.5,
    seriiDefault: 4,
    repetariDefault: 10,
  },
  {
    id: 'extensii-jm-press',
    nume: 'Extensii JM press',
    categorie: 'brate',
    grupe: ['triceps'],
    dificultate: 'greu',
    echipament: 'bara',
    met: 4.5,
    caloriiPeMinut: 5.0,
    seriiDefault: 3,
    repetariDefault: 10,
  },
  {
    id: 'genuflexiuni-frontale-cu-bara',
    nume: 'Genuflexiuni frontale cu bara',
    categorie: 'picioare',
    grupe: ['cvadriceps', 'fesieri', 'abdomen'],
    dificultate: 'greu',
    echipament: 'bara',
    met: 6.0,
    caloriiPeMinut: 6.6,
    seriiDefault: 4,
    repetariDefault: 8,
  },
  {
    id: 'genuflexiuni-bulgare-cu-gantere',
    nume: 'Genuflexiuni bulgare cu gantere',
    categorie: 'picioare',
    grupe: ['cvadriceps', 'fesieri', 'ischiogambieri'],
    dificultate: 'greu',
    echipament: 'gantere',
    met: 5.8,
    caloriiPeMinut: 6.4,
    seriiDefault: 4,
    repetariDefault: 10,
  },
  {
    id: 'genuflexiuni-hack-squat',
    nume: 'Genuflexiuni Hack squat',
    categorie: 'picioare',
    grupe: ['cvadriceps', 'fesieri'],
    dificultate: 'mediu',
    echipament: 'aparat',
    met: 5.5,
    caloriiPeMinut: 6.1,
    seriiDefault: 4,
    repetariDefault: 10,
  },
  {
    id: 'presa-de-picioare',
    nume: 'Presa de picioare',
    categorie: 'picioare',
    grupe: ['cvadriceps', 'fesieri'],
    dificultate: 'mediu',
    echipament: 'aparat',
    met: 5.5,
    caloriiPeMinut: 6.1,
    seriiDefault: 4,
    repetariDefault: 12,
  },
  {
    id: 'extensii-de-coapsa-la-aparat',
    nume: 'Extensii de coapsa la aparat',
    categorie: 'picioare',
    grupe: ['cvadriceps'],
    dificultate: 'usor',
    echipament: 'aparat',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 4,
    repetariDefault: 15,
  },
  {
    id: 'flexii-de-coapsa-culcat-la-aparat',
    nume: 'Flexii de coapsa culcat la aparat',
    categorie: 'picioare',
    grupe: ['ischiogambieri'],
    dificultate: 'usor',
    echipament: 'aparat',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 4,
    repetariDefault: 15,
  },
  {
    id: 'flexii-de-coapsa-sezand-la-aparat',
    nume: 'Flexii de coapsa sezand la aparat',
    categorie: 'picioare',
    grupe: ['ischiogambieri'],
    dificultate: 'usor',
    echipament: 'aparat',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 4,
    repetariDefault: 15,
  },
  {
    id: 'nordic-hamstring-curl',
    nume: 'Nordic hamstring curl',
    categorie: 'picioare',
    grupe: ['ischiogambieri', 'fesieri'],
    dificultate: 'greu',
    echipament: 'greutate corporala',
    met: 5.0,
    caloriiPeMinut: 5.5,
    seriiDefault: 3,
    repetariDefault: 8,
  },
  {
    id: 'hip-thrust-cu-bara',
    nume: 'Hip thrust cu bara',
    categorie: 'picioare',
    grupe: ['fesieri', 'ischiogambieri'],
    dificultate: 'mediu',
    echipament: 'bara',
    met: 5.5,
    caloriiPeMinut: 6.1,
    seriiDefault: 4,
    repetariDefault: 12,
  },
  {
    id: 'glute-bridge-pe-un-picior',
    nume: 'Glute bridge pe un picior',
    categorie: 'picioare',
    grupe: ['fesieri', 'ischiogambieri'],
    dificultate: 'usor',
    echipament: 'greutate corporala',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'kickback-de-fesier-la-cablu',
    nume: 'Kickback de fesier la cablu',
    categorie: 'picioare',
    grupe: ['fesieri'],
    dificultate: 'usor',
    echipament: 'cablu',
    met: 3.8,
    caloriiPeMinut: 4.2,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'fandari-mergand-cu-gantere',
    nume: 'Fandari mergand cu gantere',
    categorie: 'picioare',
    grupe: ['cvadriceps', 'fesieri', 'ischiogambieri'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 6.0,
    caloriiPeMinut: 6.6,
    seriiDefault: 3,
    repetariDefault: 20,
  },
  {
    id: 'fandari-inverse-cu-bara',
    nume: 'Fandari inverse cu bara',
    categorie: 'picioare',
    grupe: ['cvadriceps', 'fesieri'],
    dificultate: 'mediu',
    echipament: 'bara',
    met: 5.8,
    caloriiPeMinut: 6.4,
    seriiDefault: 4,
    repetariDefault: 10,
  },
  {
    id: 'pasire-pe-cutie-step-up',
    nume: 'Pasire pe cutie (step-up)',
    categorie: 'picioare',
    grupe: ['cvadriceps', 'fesieri'],
    dificultate: 'mediu',
    echipament: 'cutie',
    met: 5.5,
    caloriiPeMinut: 6.1,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'genuflexiuni-sissy',
    nume: 'Genuflexiuni sissy',
    categorie: 'picioare',
    grupe: ['cvadriceps'],
    dificultate: 'greu',
    echipament: 'greutate corporala',
    met: 4.5,
    caloriiPeMinut: 5.0,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'genuflexiuni-cu-goblet',
    nume: 'Genuflexiuni cu goblet',
    categorie: 'picioare',
    grupe: ['cvadriceps', 'fesieri', 'abdomen'],
    dificultate: 'usor',
    echipament: 'gantera',
    met: 5.2,
    caloriiPeMinut: 5.7,
    seriiDefault: 4,
    repetariDefault: 12,
  },
  {
    id: 'genuflexiuni-la-perete-wall-sit',
    nume: 'Genuflexiuni la perete (wall sit)',
    categorie: 'picioare',
    grupe: ['cvadriceps'],
    dificultate: 'usor',
    echipament: 'greutate corporala',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 3,
    repetariDefault: 1,
  },
  {
    id: 'plank-frontal',
    nume: 'Plank frontal',
    categorie: 'abdomen',
    grupe: ['abdomen', 'lombari'],
    dificultate: 'usor',
    echipament: 'greutate corporala',
    met: 3.2,
    caloriiPeMinut: 3.5,
    seriiDefault: 3,
    repetariDefault: 1,
  },
  {
    id: 'hollow-body-hold',
    nume: 'Hollow body hold',
    categorie: 'abdomen',
    grupe: ['abdomen'],
    dificultate: 'mediu',
    echipament: 'greutate corporala',
    met: 3.5,
    caloriiPeMinut: 3.9,
    seriiDefault: 3,
    repetariDefault: 1,
  },
  {
    id: 'ridicari-de-picioare-la-bara-fixa',
    nume: 'Ridicari de picioare la bara fixa',
    categorie: 'abdomen',
    grupe: ['abdomen', 'oblici', 'antebrate'],
    dificultate: 'greu',
    echipament: 'bara fixa',
    met: 4.5,
    caloriiPeMinut: 5.0,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'ab-wheel-rollout-v3',
    nume: 'Ab wheel rollout',
    categorie: 'abdomen',
    grupe: ['abdomen', 'lombari'],
    dificultate: 'greu',
    echipament: 'roata abdominala',
    met: 4.5,
    caloriiPeMinut: 5.0,
    seriiDefault: 3,
    repetariDefault: 10,
  },
  {
    id: 'crunch-la-cablu-in-genunchi',
    nume: 'Crunch la cablu in genunchi',
    categorie: 'abdomen',
    grupe: ['abdomen'],
    dificultate: 'mediu',
    echipament: 'cablu',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 4,
    repetariDefault: 15,
  },
  {
    id: 'dead-bug-v3',
    nume: 'Dead bug',
    categorie: 'abdomen',
    grupe: ['abdomen', 'lombari'],
    dificultate: 'usor',
    echipament: 'greutate corporala',
    met: 3.0,
    caloriiPeMinut: 3.3,
    seriiDefault: 3,
    repetariDefault: 12,
  },
  {
    id: 'mountain-climbers-v3',
    nume: 'Mountain climbers',
    categorie: 'abdomen',
    grupe: ['abdomen', 'oblici', 'cardio'],
    dificultate: 'mediu',
    echipament: 'greutate corporala',
    met: 7.0,
    caloriiPeMinut: 7.7,
    seriiDefault: 3,
    repetariDefault: 30,
  },
  {
    id: 'v-up',
    nume: 'V-up',
    categorie: 'abdomen',
    grupe: ['abdomen'],
    dificultate: 'mediu',
    echipament: 'greutate corporala',
    met: 4.0,
    caloriiPeMinut: 4.4,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'toes-to-bar',
    nume: 'Toes to bar',
    categorie: 'abdomen',
    grupe: ['abdomen', 'antebrate'],
    dificultate: 'greu',
    echipament: 'bara fixa',
    met: 5.0,
    caloriiPeMinut: 5.5,
    seriiDefault: 3,
    repetariDefault: 10,
  },
  {
    id: 'sarituri-cu-coarda',
    nume: 'Sarituri cu coarda',
    categorie: 'cardio',
    grupe: ['cardio', 'gambe'],
    dificultate: 'mediu',
    echipament: 'coarda',
    met: 10.0,
    caloriiPeMinut: 11.0,
    seriiDefault: 3,
    repetariDefault: 1,
  },
  {
    id: 'burpees-v3',
    nume: 'Burpees',
    categorie: 'cardio',
    grupe: ['corp_intreg', 'cardio'],
    dificultate: 'greu',
    echipament: 'greutate corporala',
    met: 9.0,
    caloriiPeMinut: 9.9,
    seriiDefault: 3,
    repetariDefault: 15,
  },
  {
    id: 'sprint-pe-loc-cu-genunchii-sus',
    nume: 'Sprint pe loc cu genunchii sus',
    categorie: 'cardio',
    grupe: ['cardio', 'cvadriceps'],
    dificultate: 'mediu',
    echipament: 'greutate corporala',
    met: 8.0,
    caloriiPeMinut: 8.8,
    seriiDefault: 3,
    repetariDefault: 30,
  },
  {
    id: 'vaslit-la-ergometru',
    nume: 'Vaslit la ergometru',
    categorie: 'cardio',
    grupe: ['cardio', 'dorsali', 'cvadriceps'],
    dificultate: 'mediu',
    echipament: 'aparat',
    met: 8.5,
    caloriiPeMinut: 9.4,
    seriiDefault: 1,
    repetariDefault: 1,
  },
  {
    id: 'bicicleta-eliptica',
    nume: 'Bicicleta eliptica',
    categorie: 'cardio',
    grupe: ['cardio', 'cvadriceps'],
    dificultate: 'usor',
    echipament: 'aparat',
    met: 6.5,
    caloriiPeMinut: 7.2,
    seriiDefault: 1,
    repetariDefault: 1,
  },
  {
    id: 'battle-ropes-v3',
    nume: 'Battle ropes',
    categorie: 'cardio',
    grupe: ['cardio', 'deltoid anterior', 'antebrate'],
    dificultate: 'greu',
    echipament: 'frenghii',
    met: 9.5,
    caloriiPeMinut: 10.5,
    seriiDefault: 4,
    repetariDefault: 1,
  },
  {
    id: 'kettlebell-swing-v3',
    nume: 'Kettlebell swing',
    categorie: 'full-body',
    grupe: ['fesieri', 'ischiogambieri', 'lombari'],
    dificultate: 'mediu',
    echipament: 'kettlebell',
    met: 8.0,
    caloriiPeMinut: 8.8,
    seriiDefault: 4,
    repetariDefault: 20,
  },
  {
    id: 'box-jump',
    nume: 'Box jump',
    categorie: 'cardio',
    grupe: ['cvadriceps', 'fesieri', 'gambe'],
    dificultate: 'mediu',
    echipament: 'cutie',
    met: 8.0,
    caloriiPeMinut: 8.8,
    seriiDefault: 4,
    repetariDefault: 10,
  },
  {
    id: 'sled-push',
    nume: 'Sled push',
    categorie: 'full-body',
    grupe: ['cvadriceps', 'fesieri', 'gambe'],
    dificultate: 'greu',
    echipament: 'sanie',
    met: 9.0,
    caloriiPeMinut: 9.9,
    seriiDefault: 4,
    repetariDefault: 1,
  },
  {
    id: 'assault-bike',
    nume: 'Assault bike',
    categorie: 'cardio',
    grupe: ['cardio', 'cvadriceps', 'deltoid anterior'],
    dificultate: 'greu',
    echipament: 'aparat',
    met: 9.5,
    caloriiPeMinut: 10.5,
    seriiDefault: 1,
    repetariDefault: 1,
  },
  {
    id: 'stair-climber',
    nume: 'Stair climber',
    categorie: 'cardio',
    grupe: ['cardio', 'fesieri', 'cvadriceps'],
    dificultate: 'mediu',
    echipament: 'aparat',
    met: 7.5,
    caloriiPeMinut: 8.2,
    seriiDefault: 1,
    repetariDefault: 1,
  },
  {
    id: 'thruster-cu-gantere',
    nume: 'Thruster cu gantere',
    categorie: 'full-body',
    grupe: ['cvadriceps', 'deltoid anterior', 'fesieri'],
    dificultate: 'greu',
    echipament: 'gantere',
    met: 8.5,
    caloriiPeMinut: 9.4,
    seriiDefault: 4,
    repetariDefault: 12,
  },
  {
    id: 'clean-and-press-cu-bara',
    nume: 'Clean and press cu bara',
    categorie: 'full-body',
    grupe: ['corp_intreg', 'trapez', 'deltoid anterior'],
    dificultate: 'greu',
    echipament: 'bara',
    met: 8.0,
    caloriiPeMinut: 8.8,
    seriiDefault: 4,
    repetariDefault: 6,
  },
  {
    id: 'turkish-get-up-v3',
    nume: 'Turkish get-up',
    categorie: 'full-body',
    grupe: ['abdomen', 'deltoid anterior', 'oblici'],
    dificultate: 'greu',
    echipament: 'kettlebell',
    met: 6.0,
    caloriiPeMinut: 6.6,
    seriiDefault: 3,
    repetariDefault: 5,
  },
  {
    id: 'bear-crawl-v3',
    nume: 'Bear crawl',
    categorie: 'full-body',
    grupe: ['abdomen', 'deltoid anterior', 'cvadriceps'],
    dificultate: 'mediu',
    echipament: 'greutate corporala',
    met: 6.5,
    caloriiPeMinut: 7.2,
    seriiDefault: 3,
    repetariDefault: 1,
  },
  {
    id: 'cat-cow-v3',
    nume: 'Cat-cow',
    categorie: 'mobilitate',
    grupe: ['mobilitate', 'lombari'],
    dificultate: 'usor',
    echipament: 'greutate corporala',
    met: 2.5,
    caloriiPeMinut: 2.8,
    seriiDefault: 2,
    repetariDefault: 12,
  },
  {
    id: 'stretching-de-ischiogambieri-sezand',
    nume: 'Stretching de ischiogambieri sezand',
    categorie: 'mobilitate',
    grupe: ['mobilitate', 'ischiogambieri'],
    dificultate: 'usor',
    echipament: 'greutate corporala',
    met: 2.3,
    caloriiPeMinut: 2.5,
    seriiDefault: 2,
    repetariDefault: 1,
  },
  {
    id: 'deschidere-de-sold-in-fandare-hip-flexor-stretch',
    nume: 'Deschidere de sold in fandare (hip flexor stretch)',
    categorie: 'mobilitate',
    grupe: ['mobilitate', 'fesieri'],
    dificultate: 'usor',
    echipament: 'greutate corporala',
    met: 2.5,
    caloriiPeMinut: 2.8,
    seriiDefault: 2,
    repetariDefault: 1,
  },
  {
    id: 'rotatii-de-umeri-cu-bastonul',
    nume: 'Rotatii de umeri cu bastonul',
    categorie: 'mobilitate',
    grupe: ['mobilitate', 'deltoid posterior'],
    dificultate: 'usor',
    echipament: 'baston',
    met: 2.5,
    caloriiPeMinut: 2.8,
    seriiDefault: 2,
    repetariDefault: 12,
  },
  {
    id: 'thoracic-extension-pe-rola',
    nume: 'Thoracic extension pe rola',
    categorie: 'mobilitate',
    grupe: ['mobilitate', 'trapez'],
    dificultate: 'usor',
    echipament: 'rola',
    met: 2.5,
    caloriiPeMinut: 2.8,
    seriiDefault: 2,
    repetariDefault: 10,
  },
  {
    id: 'deep-squat-hold',
    nume: 'Deep squat hold',
    categorie: 'mobilitate',
    grupe: ['mobilitate', 'adductori'],
    dificultate: 'usor',
    echipament: 'greutate corporala',
    met: 2.8,
    caloriiPeMinut: 3.1,
    seriiDefault: 2,
    repetariDefault: 1,
  },
  {
    id: 'stretching-de-pectorali-la-usa',
    nume: 'Stretching de pectorali la usa',
    categorie: 'mobilitate',
    grupe: ['mobilitate', 'pectorali'],
    dificultate: 'usor',
    echipament: 'greutate corporala',
    met: 2.3,
    caloriiPeMinut: 2.5,
    seriiDefault: 2,
    repetariDefault: 1,
  },
  {
    id: '90-90-hip-rotation',
    nume: '90/90 hip rotation',
    categorie: 'mobilitate',
    grupe: ['mobilitate', 'fesieri', 'abductori'],
    dificultate: 'usor',
    echipament: 'greutate corporala',
    met: 2.5,
    caloriiPeMinut: 2.8,
    seriiDefault: 2,
    repetariDefault: 10,
  },
  {
    id: 'world-s-greatest-stretch',
    nume: 'World\'s greatest stretch',
    categorie: 'mobilitate',
    grupe: ['mobilitate', 'adductori', 'lombari'],
    dificultate: 'usor',
    echipament: 'greutate corporala',
    met: 3.0,
    caloriiPeMinut: 3.3,
    seriiDefault: 2,
    repetariDefault: 8,
  },
  {
    id: 'foam-rolling-cvadriceps',
    nume: 'Foam rolling cvadriceps',
    categorie: 'mobilitate',
    grupe: ['mobilitate', 'cvadriceps'],
    dificultate: 'usor',
    echipament: 'rola',
    met: 2.3,
    caloriiPeMinut: 2.5,
    seriiDefault: 2,
    repetariDefault: 1,
  },
];
