import type { Exercitiu } from './exercitii';

export const NEW_EXERCISES: Exercitiu[] = [
  {
    id: 'pec-deck',
    nume: 'Pec Deck Machine',
    categorie: 'piept',
    grupe: ['pectorali', 'deltoid anterior'],
    dificultate: 'usor',
    echipament: 'aparat',
    met: 4,
    caloriiPeMinut: 5,
    seriiDefault: 3,
    repetariDefault: 12,
    muschiTinta: { pectorali: 100, deltoid_anterior: 40 },
    descriere: 'Izolare excelenta pentru piept folosind aparatul pec deck.',
    instructiuni: ['Tine spatele lipit de banca.', 'Adu bratele in fata contractand pieptul.'],
  },
  {
    id: 'chest-press-gantere',
    nume: 'Impins cu gantere pe plan drept',
    categorie: 'piept',
    grupe: ['pectorali', 'triceps', 'deltoid anterior'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 5,
    caloriiPeMinut: 7,
    seriiDefault: 4,
    repetariDefault: 10,
    muschiTinta: { pectorali: 100, triceps: 60, deltoid_anterior: 50 },
    descriere: 'Alternativa la bara pentru libertate mai mare de miscare.',
  },
  {
    id: 'flotari-decline',
    nume: 'Flotari cu picioarele ridicate',
    categorie: 'piept',
    grupe: ['pectoral superior', 'triceps', 'deltoid anterior'],
    dificultate: 'mediu',
    echipament: 'corp',
    met: 5,
    caloriiPeMinut: 6,
    seriiDefault: 3,
    repetariDefault: 15,
    muschiTinta: { pectorali: 90, triceps: 70, deltoid_anterior: 60 },
  },
  {
    id: 'pulldown-priza-ingusta',
    nume: 'Traciuni la helcometru priza ingusta',
    categorie: 'spate',
    grupe: ['dorsali', 'biceps', 'romboizi'],
    dificultate: 'mediu',
    echipament: 'aparat',
    met: 5,
    caloriiPeMinut: 6,
    seriiDefault: 4,
    repetariDefault: 12,
    muschiTinta: { dorsali: 100, biceps: 70, romboizi: 60 },
  },
  {
    id: 'pullups-greutate',
    nume: 'Tractiuni cu greutate',
    categorie: 'spate',
    grupe: ['dorsali', 'biceps', 'trapez'],
    dificultate: 'greu',
    echipament: 'corp+greutate',
    met: 7,
    caloriiPeMinut: 9,
    seriiDefault: 3,
    repetariDefault: 8,
    muschiTinta: { dorsali: 100, biceps: 80, trapez: 50 },
  },
  {
    id: 'ramat-cablu-un-brat',
    nume: 'Ramat la cablu cu un singur brat',
    categorie: 'spate',
    grupe: ['dorsali', 'romboizi'],
    dificultate: 'usor',
    echipament: 'cablu',
    met: 4,
    caloriiPeMinut: 5,
    seriiDefault: 3,
    repetariDefault: 12,
    muschiTinta: { dorsali: 100, romboizi: 50 },
  },
  {
    id: 'hack-squat',
    nume: 'Hack Squat',
    categorie: 'picioare',
    grupe: ['cvadriceps', 'fesieri'],
    dificultate: 'mediu',
    echipament: 'aparat',
    met: 6,
    caloriiPeMinut: 8,
    seriiDefault: 4,
    repetariDefault: 10,
    muschiTinta: { cvadriceps: 100, fesieri: 70 },
  },
  {
    id: 'leg-curl-sezand',
    nume: 'Flexii femurali sezand',
    categorie: 'picioare',
    grupe: ['ischiogambieri'],
    dificultate: 'usor',
    echipament: 'aparat',
    met: 4,
    caloriiPeMinut: 5,
    seriiDefault: 3,
    repetariDefault: 15,
    muschiTinta: { ischiogambieri: 100 },
  },
  {
    id: 'calf-raise-sezand',
    nume: 'Ridicari pe varfuri din sezut',
    categorie: 'picioare',
    grupe: ['gambe'],
    dificultate: 'usor',
    echipament: 'aparat',
    met: 3,
    caloriiPeMinut: 4,
    seriiDefault: 4,
    repetariDefault: 20,
    muschiTinta: { gambe: 100 },
  },
  {
    id: 'abductori-masina',
    nume: 'Abductori la aparat (coapse exterior)',
    categorie: 'picioare',
    grupe: ['fesieri', 'abductori'],
    dificultate: 'usor',
    echipament: 'aparat',
    met: 3,
    caloriiPeMinut: 4,
    seriiDefault: 3,
    repetariDefault: 15,
    muschiTinta: { fesieri: 100, abductori: 80 },
  },
  {
    id: 'adductori-masina',
    nume: 'Adductori la aparat (coapse interior)',
    categorie: 'picioare',
    grupe: ['adductori'],
    dificultate: 'usor',
    echipament: 'aparat',
    met: 3,
    caloriiPeMinut: 4,
    seriiDefault: 3,
    repetariDefault: 15,
    muschiTinta: { adductori: 100 },
  },
  {
    id: 'military-press',
    nume: 'Military Press cu bara in picioare',
    categorie: 'umeri',
    grupe: ['deltoid anterior', 'deltoid lateral', 'triceps', 'core'],
    dificultate: 'greu',
    echipament: 'bara',
    met: 6,
    caloriiPeMinut: 7,
    seriiDefault: 4,
    repetariDefault: 8,
    muschiTinta: { deltoid_anterior: 100, deltoid_lateral: 60, triceps: 70, abdomen: 40 },
  },
  {
    id: 'ridicari-laterale-cablu',
    nume: 'Ridicari laterale la cablu',
    categorie: 'umeri',
    grupe: ['deltoid lateral'],
    dificultate: 'mediu',
    echipament: 'cablu',
    met: 4,
    caloriiPeMinut: 5,
    seriiDefault: 4,
    repetariDefault: 15,
    muschiTinta: { deltoid_lateral: 100 },
  },
  {
    id: 'reverse-pec-deck',
    nume: 'Fluturari inverse la aparat',
    categorie: 'umeri',
    grupe: ['deltoid posterior', 'romboizi', 'trapez'],
    dificultate: 'usor',
    echipament: 'aparat',
    met: 4,
    caloriiPeMinut: 5,
    seriiDefault: 3,
    repetariDefault: 12,
    muschiTinta: { deltoid_posterior: 100, romboizi: 80, trapez: 50 },
  },
  {
    id: 'flexii-spider',
    nume: 'Flexii Spider',
    categorie: 'brate',
    grupe: ['biceps'],
    dificultate: 'mediu',
    echipament: 'gantere',
    met: 4,
    caloriiPeMinut: 5,
    seriiDefault: 3,
    repetariDefault: 10,
    muschiTinta: { biceps: 100 },
  },
  {
    id: 'flexii-cablu',
    nume: 'Flexii biceps la cablu',
    categorie: 'brate',
    grupe: ['biceps'],
    dificultate: 'usor',
    echipament: 'cablu',
    met: 4,
    caloriiPeMinut: 5,
    seriiDefault: 3,
    repetariDefault: 15,
    muschiTinta: { biceps: 100 },
  },
  {
    id: 'triceps-pushdown-funie',
    nume: 'Extensii triceps cu sfoara',
    categorie: 'brate',
    grupe: ['triceps'],
    dificultate: 'usor',
    echipament: 'cablu',
    met: 4,
    caloriiPeMinut: 5,
    seriiDefault: 4,
    repetariDefault: 12,
    muschiTinta: { triceps: 100 },
  },
  {
    id: 'french-press',
    nume: 'Presa Franceza',
    categorie: 'brate',
    grupe: ['triceps'],
    dificultate: 'mediu',
    echipament: 'bara',
    met: 4,
    caloriiPeMinut: 5,
    seriiDefault: 3,
    repetariDefault: 10,
    muschiTinta: { triceps: 100 },
  },
  {
    id: 'ab-wheel-rollout',
    nume: 'Roata pentru abdomen',
    categorie: 'abdomen',
    grupe: ['abdomen', 'core'],
    dificultate: 'greu',
    echipament: 'roata',
    met: 5,
    caloriiPeMinut: 6,
    seriiDefault: 3,
    repetariDefault: 10,
    muschiTinta: { abdomen: 100, dorsali: 40 },
  },
  {
    id: 'cable-crunch',
    nume: 'Aplecari la cablu (Cable Crunch)',
    categorie: 'abdomen',
    grupe: ['abdomen'],
    dificultate: 'mediu',
    echipament: 'cablu',
    met: 4,
    caloriiPeMinut: 5,
    seriiDefault: 3,
    repetariDefault: 15,
    muschiTinta: { abdomen: 100 },
  }
];
