import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const root = resolve(scriptDir, '..');

function attributes(tag) {
  const output = {};
  for (const match of tag.matchAll(/([\w:-]+)="([^"]*)"/g)) output[match[1]] = match[2];
  return output;
}

function parseSvg(source, expectedView) {
  const svgTag = source.match(/<svg\b[^>]*>/)?.[0];
  if (!svgTag) throw new Error(`Missing svg root for ${expectedView}`);
  const viewBoxValue = attributes(svgTag).viewBox;
  const viewBox = viewBoxValue?.split(/\s+/).map(Number);
  if (!viewBox || viewBox.length !== 4 || viewBox.some((value) => !Number.isFinite(value))) {
    throw new Error(`Invalid viewBox for ${expectedView}`);
  }

  const shapes = [...source.matchAll(/<path\b[^>]*\/>/g)].map((match) => {
    const attrs = attributes(match[0]);
    if (!attrs.id || !attrs.d || !attrs.fill) throw new Error(`Invalid path in ${expectedView}`);
    const shape = { id: attrs.id, d: attrs.d, fill: attrs.fill };
    if (attrs['data-muscle']) {
      if (attrs['data-view'] !== expectedView) throw new Error(`Wrong view on ${attrs.id}`);
      if (!['left', 'right', 'center'].includes(attrs['data-side'])) {
        throw new Error(`Invalid side on ${attrs.id}`);
      }
      shape.muscleId = attrs['data-muscle'];
      shape.view = attrs['data-view'];
      shape.side = attrs['data-side'];
    }
    return shape;
  });

  if (shapes.length < 2) throw new Error(`No anatomy paths for ${expectedView}`);
  const ids = shapes.map((shape) => shape.id);
  if (new Set(ids).size !== ids.length) throw new Error(`Duplicate path id in ${expectedView}`);
  return { view: expectedView, viewBox, shapes };
}

async function build(view, sourceName, outputName, constantName) {
  const source = await readFile(resolve(root, 'assets/anatomy-v2', sourceName), 'utf8');
  const parsed = parseSvg(source, view);
  const outputPath = resolve(root, 'components/workout-v2', outputName);
  await mkdir(dirname(outputPath), { recursive: true });
  const contents = `/* AUTO-GENERATED by scripts/buildAnatomyV2.mjs. */\n` +
    `import type { AnatomyV2Source } from './anatomyV2Types';\n\n` +
    `export const ${constantName} = ${JSON.stringify(parsed, null, 2)} as const satisfies AnatomyV2Source;\n`;
  await writeFile(outputPath, contents, 'utf8');
  return parsed.shapes.length;
}

const frontCount = await build('front', 'front.svg', 'anatomyV2Front.ts', 'ANATOMY_V2_FRONT');
const backCount = await build('back', 'back.svg', 'anatomyV2Back.ts', 'ANATOMY_V2_BACK');
process.stdout.write(`ANATOMY V2 BUILT: front ${frontCount} paths; back ${backCount} paths\n`);

